(function(){'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var q=ca(this);function t(a,b){if(b)a:{var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
t("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.g=h;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
t("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=q[b[c]];typeof d==="function"&&typeof d.prototype[a]!="function"&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
var ea=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function u(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.H=b.prototype}function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function la(a){return ma(a,a)}
function ma(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function w(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var na=typeof Object.assign=="function"?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)w(d,e)&&(a[e]=d[e])}return a};t("Object.assign",function(a){return a||na});function oa(){this.l=!1;this.h=null;this.i=void 0;this.g=1;this.o=0;this.j=null}
function pa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}oa.prototype.m=function(a){this.i=a};function qa(a,b){a.j={ca:b,ia:!0};a.g=a.o}oa.prototype.return=function(a){this.j={return:a};this.g=this.o};function ra(a,b,c){a.g=c;return{value:b}}function sa(a){this.g=new oa;this.h=a}function ta(a,b){pa(a.g);var c=a.g.h;if(c)return ua(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return va(a)}
function ua(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var h=e.value}catch(f){return a.g.h=null,qa(a.g,f),va(a)}a.g.h=null;d.call(a.g,h);return va(a)}function va(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,qa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.ia)throw b.ca;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function wa(a){this.next=function(b){pa(a.g);a.g.h?b=ua(a,a.g.h.next,b,a.g.m):(a.g.m(b),b=va(a));return b};this.throw=function(b){pa(a.g);a.g.h?b=ua(a,a.g.h["throw"],b,a.g.m):(qa(a.g,b),b=va(a));return b};this.return=function(b){return ta(a,b)};this[Symbol.iterator]=function(){return this}}function xa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}
function ya(a){return xa(new wa(new sa(a)))}function za(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}t("globalThis",function(a){return a||q});
t("Promise",function(a){function b(f){this.g=0;this.i=void 0;this.h=[];this.o=!1;var g=this.j();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.i(function(){g.l()})}this.g.push(f)};var e=q.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.C),reject:f(this.l)}};b.prototype.C=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.I(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.B(f):this.m(f)}};
b.prototype.B=function(f){var g=void 0;try{g=f.then}catch(k){this.l(k);return}typeof g=="function"?this.M(g,f):this.m(f)};b.prototype.l=function(f){this.s(2,f)};b.prototype.m=function(f){this.s(1,f)};b.prototype.s=function(f,g){if(this.g!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.g);this.g=f;this.i=g;this.g===2&&this.D();this.v()};b.prototype.D=function(){var f=this;e(function(){if(f.A()){var g=q.console;typeof g!=="undefined"&&g.error(f.i)}},1)};b.prototype.A=
function(){if(this.o)return!1;var f=q.CustomEvent,g=q.Event,k=q.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=q.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.v=function(){if(this.h!=null){for(var f=0;f<this.h.length;++f)h.h(this.h[f]);this.h=null}};var h=new c;b.prototype.I=
function(f){var g=this.j();f.O(g.resolve,g.reject)};b.prototype.M=function(f,g){var k=this.j();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,g){function k(r,A){return typeof r=="function"?function(G){try{l(r(G))}catch(y){m(y)}}:A}var l,m,p=new b(function(r,A){l=r;m=A});this.O(k(f,l),k(g,m));return p};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.O=function(f,g){function k(){switch(l.g){case 1:f(l.i);break;case 2:g(l.i);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;this.h==null?h.h(k):this.h.push(k);this.o=!0};b.resolve=d;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=v(f),m=l.next();!m.done;m=l.next())d(m.value).O(g,k)})};b.all=function(f){var g=v(f),k=g.next();return k.done?d([]):new b(function(l,m){function p(G){return function(y){r[G]=y;A--;A==0&&l(r)}}var r=[],A=0;do r.push(void 0),A++,d(k.value).O(p(r.length-1),m),k=g.next();while(!k.done)})};return b});
t("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
t("WeakMap",function(a){function b(k){this.g=(g+=Math.random()+1).toString();if(k){k=v(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!w(k,f)){var l=new c;ba(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(p){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!w(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&w(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&w(k,
f)&&w(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&w(k,f)&&w(k[f],this.g)?delete k[f][this.g]:!1};return b});
t("Map",function(a){function b(){var g={};return g.G=g.next=g.head=g}function c(g,k){var l=g[1];return da(function(){if(l){for(;l.head!=g[1];)l=l.G;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(g,k){var l=k&&typeof k;l=="object"||l=="function"?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&w(g[0],l))for(g=0;g<m.length;g++){var p=m[g];if(k!==k&&p.key!==p.key||k===p.key)return{id:l,list:m,index:g,u:p}}return{id:l,
list:m,index:-1,u:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=v(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(v([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(p){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.u?l.u.value=k:(l.u={next:this[1],G:this[1].G,head:this[1],key:g,value:k},l.list.push(l.u),this[1].G.next=l.u,this[1].G=l.u,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.u&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.u.G.next=g.u.next,g.u.next.G=g.u.G,g.u.head=
null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].G=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).u};e.prototype.get=function(g){return(g=d(this,g).u)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,g.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});function Aa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}t("Array.prototype.entries",function(a){return a?a:function(){return Aa(this,function(b,c){return[b,c]})}});
t("Array.prototype.keys",function(a){return a?a:function(){return Aa(this,function(b){return b})}});t("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});t("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var f=d[h];if(b.call(c,f,h,d)){b=f;break a}}b=void 0}return b}});
t("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push([d,b[d]]);return c}});t("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});t("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
t("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});t("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});t("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
t("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return(this+"").indexOf(b,c||0)!==-1}});t("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)w(b,d)&&c.push(b[d]);return c}});
t("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});t("Array.prototype.values",function(a){return a?a:function(){return Aa(this,function(b,c){return c})}});
t("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ba=Ba||{},x=this||self;function Ca(a,b){a=a.split(".");for(var c=x,d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Da(a,b){a=a.split(".");b=b||x;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b}function Ea(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}function Fa(a){var b=Ea(a);return b=="array"||b=="object"&&typeof a.length=="number"}
function Ga(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}var Ha="closure_uid_"+(Math.random()*1E9>>>0),Ia=0;function Ja(a,b,c){return a.call.apply(a.bind,arguments)}function Ka(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function z(a,b,c){z=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Ja:Ka;return z.apply(null,arguments)}function B(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function La(a){(0,eval)(a)}
function C(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.xa=function(d,e,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[e].apply(d,f)}};function D(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b);this.g=!0}C(D,Error);D.prototype.name="CustomError";var Ma;var Na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Oa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Pa=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function Qa(a,b){b=Na(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function Ra(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Sa(a){var b=Da("window.location.href");a==null&&(a='Unknown Error of type "null/undefined"');if(typeof a==="string")return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"};var c=!1;try{var d=a.lineNumber||a.line||"Not available"}catch(f){d="Not available",c=!0}try{var e=a.fileName||a.filename||a.sourceURL||x.$googDebugFname||b}catch(f){e="Not available",c=!0}b=Ta(a);if(!(!c&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name)){c=a.message;if(c==
null){if(a.constructor&&a.constructor instanceof Function){if(a.constructor.name)c=a.constructor.name;else if(c=a.constructor,Ua[c])c=Ua[c];else{c=String(c);if(!Ua[c]){var h=/function\s+([^\(]+)/m.exec(c);Ua[c]=h?h[1]:"[Anonymous]"}c=Ua[c]}c='Unknown Error of type "'+c+'"'}else c="Unknown Error of unknown type";typeof a.toString==="function"&&Object.prototype.toString!==a.toString&&(c+=": "+a.toString())}return{message:c,name:a.name||"UnknownError",lineNumber:d,fileName:e,stack:b||"Not available"}}return{message:a.message,
name:a.name,lineNumber:a.lineNumber,fileName:a.fileName,stack:b}}
function Ta(a,b){b||(b={});b[Va(a)]=!0;var c=a.stack||"",d=a.cause;d&&!b[Va(d)]&&(c+="\nCaused by: ",d.stack&&d.stack.indexOf(d.toString())==0||(c+=typeof d==="string"?d:d.message+"\n"),c+=Ta(d,b));a=a.errors;if(Array.isArray(a)){d=1;var e;for(e=0;e<a.length&&!(d>4);e++)b[Va(a[e])]||(c+="\nInner error "+d++ +": ",a[e].stack&&a[e].stack.indexOf(a[e].toString())==0||(c+=typeof a[e]==="string"?a[e]:a[e].message+"\n"),c+=Ta(a[e],b));e<a.length&&(c+="\n... "+(a.length-e)+" more inner errors")}return c}
function Va(a){var b="";typeof a.toString==="function"&&(b=""+a);return b+a.stack}var Ua={};function Wa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Xa(a){var b={},c;for(c in a)b[c]=a[c];return b}var Ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Za(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<Ya.length;h++)c=Ya[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var $a=globalThis.trustedTypes,ab;function bb(){var a=null;if(!$a)return a;try{var b=function(c){return c};a=$a.createPolicy("asx-frontend#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};function cb(a){this.g=a}cb.prototype.toString=function(){return this.g+""};function db(a){var b;ab===void 0&&(ab=bb());a=(b=ab)?b.createScriptURL(a):a;return new cb(a)}function eb(a){if(a instanceof cb)return a.g;throw Error("");};var fb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function gb(a,b){b=fb.test(b)?b:void 0;b!==void 0&&a.open(b,void 0,void 0)}function hb(a){a=a===void 0?document:a;var b,c;a=(c=(b=a).querySelector)==null?void 0:c.call(b,"script[nonce]");return a==null?"":a.nonce||a.getAttribute("nonce")||""};function ib(a,b){a.src=eb(b);(b=hb(a.ownerDocument))&&a.setAttribute("nonce",b)};var jb,kb=Da("CLOSURE_FLAGS"),lb=kb&&kb[1981196515];jb=lb!=null?lb:!1;function mb(){var a=x.navigator;return a&&(a=a.userAgent)?a:""};var nb=mb().toLowerCase().indexOf("webkit")!=-1&&mb().indexOf("Edge")==-1&&mb().indexOf("Mobile")!=-1;function ob(a){var b=za.apply(1,arguments);if(b.length===0)return db(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return db(c)};function pb(a,b){Wa(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:qb.hasOwnProperty(d)?a.setAttribute(qb[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})}var qb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function rb(a,b,c){var d=arguments,e=document,h=d[1],f=sb(e,String(d[0]));h&&(typeof h==="string"?f.className=h:Array.isArray(h)?f.className=h.join(" "):pb(f,h));d.length>2&&tb(e,f,d,2);return f}
function tb(a,b,c,d){function e(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(;d<c.length;d++){var h=c[d];if(!Fa(h)||Ga(h)&&h.nodeType>0)e(h);else{a:{if(h&&typeof h.length=="number"){if(Ga(h)){var f=typeof h.item=="function"||typeof h.item=="string";break a}if(typeof h==="function"){f=typeof h.item=="function";break a}}f=!1}Oa(f?Ra(h):h,e)}}}function sb(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}
function ub(a){return a.nodeType==9?a:a.ownerDocument||a.document}function vb(a){this.g=a||x.document||document}vb.prototype.append=function(a,b){tb(ub(a),a,arguments,1)};function wb(a){x.setTimeout(function(){throw a;},0)};var xb=typeof x.BigInt==="function"&&typeof x.BigInt(0)==="bigint";var yb=Number.MIN_SAFE_INTEGER.toString(),zb=xb?BigInt(Number.MIN_SAFE_INTEGER):void 0,Ab=Number.MAX_SAFE_INTEGER.toString(),Bb=xb?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Cb(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Db=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Eb(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Fb=Eb("jas",void 0,!0),Gb=Eb(void 0,"0actk"),Hb=Eb("m_m","za",!0);var Ib=Math.max,Jb=Ib.apply,Kb=Object.values({ra:1,qa:2,pa:4,ua:8,wa:16,sa:32,ka:64,na:128,la:256,va:512,ma:1024,oa:2048,ta:4096}),Lb;if(Kb instanceof Array)Lb=Kb;else{for(var Mb=v(Kb),Nb,Ob=[];!(Nb=Mb.next()).done;)Ob.push(Nb.value);Lb=Ob}Jb.call(Ib,Math,Lb);var Pb={ha:{value:0,configurable:!0,writable:!0,enumerable:!1}},Qb=Object.defineProperties,E=Db?Fb:"ha";function Rb(a,b){Db||E in a||Qb(a,Pb);a[E]|=b}function Sb(a,b){Db||E in a||Qb(a,Pb);a[E]=b};var Tb={};function Ub(a,b){return b===void 0?a.h!==Vb&&!!(2&(a.g[E]|0)):!!(2&b)&&a.h!==Vb}var Vb={};var Wb=void 0;function Xb(a){return a.displayName||a.name||"unknown type name"};function Yb(a){return a};function Zb(a,b,c,d){var e=d!==void 0;d=!!d;var h=[],f=a.length,g=4294967295,k=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var p=f&&a[f-1];p!=null&&typeof p==="object"&&p.constructor===Object?(f--,g=f):p=void 0;if(l&&!(b&128)&&!e){k=!0;var r;g=((r=$b)!=null?r:Yb)(g-m,m,a,p)+m}}b=void 0;for(e=0;e<f;e++)if(r=a[e],r!=null&&(r=c(r,d))!=null)if(l&&e>=g){var A=e-m,G=void 0;((G=b)!=null?G:b={})[A]=r}else h[e]=r;if(p)for(var y in p)a=p[y],a!=null&&(a=c(a,d))!=null&&(f=+y,e=void 0,l&&!Number.isNaN(f)&&
(e=f+m)<g?h[e]=a:(f=void 0,((f=b)!=null?f:b={})[y]=a));b&&(k?h.push(b):h[g]=b);return h}function ac(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(xb?a>=zb&&a<=Bb:a[0]==="-"?Cb(a,yb):Cb(a,Ab))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[E]|0;return a.length===0&&b&1?void 0:Zb(a,b,ac)}if(a[Hb]===Tb)return bc(a);return}return a}var $b;function bc(a){a=a.g;return Zb(a,a[E]|0,ac)};function cc(a,b,c){var d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-8380417|(b&1023)<<13)}else{if(!Array.isArray(a))throw Error("narr");e=a[E]|0;2048&e&&!(2&e)&&dc();if(e&256)throw Error("farr");if(e&64)return d!==0||e&2048||Sb(a,e|2048),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var h=c.length;if(h){var f=h-1,g=c[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){b=e&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var k in g)h=+k,h<f&&(c[h+b]=g[k],
delete g[k]);e=e&-8380417|(f&1023)<<13;break a}}if(b){k=Math.max(b,h-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-8380417|(k&1023)<<13}}}e|=64;d===0&&(e|=2048);Sb(a,e);return a}function dc(){if(Gb!=null){var a;var b=(a=Wb)!=null?a:Wb={};a=b[Gb]||0;a>=5||(b[Gb]=a+1,b=Error(),b.__closure__error__context__984382||(b.__closure__error__context__984382={}),b.__closure__error__context__984382.severity="incident",wb(b))}};function ec(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[E]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=fc(a,c,!1,b&&!(c&16)):(Rb(a,34),c&4&&Object.freeze(a)));return a}if(a[Hb]===Tb){b=a.g;var d=b[E]|0;Ub(a,d)?c=a:c=fc(b,d);return c}}function fc(a,b,c,d){d!=null||(d=!!(34&b));a=Zb(a,b,ec,d);d=32;c&&(d|=2);b=b&8380609|d;Sb(a,b);return a}function hc(a){if(a.h!==Vb)return!1;var b=a.g;b=fc(b,b[E]|0);Rb(b,2048);a.g=b;a.h=void 0;a.i=void 0;return!0}
function ic(a){if(!hc(a)&&Ub(a,a.g[E]|0))throw Error();};function jc(a,b,c){if(b===-1)return null;var d=b+-1,e=a.length-1;if(!(e<0)){if(d>=e){var h=a[e];if(h!=null&&typeof h==="object"&&h.constructor===Object){e=h[b];var f=!0}else if(d===e)e=h;else return}else e=a[d];if(c&&e!=null){c=c(e);if(c==null)return c;if(!Object.is(c,e))return f?h[b]=c:a[d]=c,c}return e}}
function kc(a,b,c,d){var e=c+-1,h=a.length-1;if(h>=0&&e>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object){f[c]=d;return}}e<=h?a[e]=d:d!==void 0&&(b=(b!=null?b:a[E]|0)>>13&1023||536870912,c>=b?d!=null&&(e={},a[b+-1]=(e[c]=d,e)):a[e]=d)}function lc(a,b){var c=mc;a=jc(a,1,function(d){if(d==null||typeof d!=="object"||d[Hb]!==Tb)if(Array.isArray(d)){var e=d[E]|0;var h=e|b&32;h|=b&2;h!==e&&Sb(d,h);d=new c(d)}else d=void 0;return d});if(a!=null)return a}
function F(a,b){var c=c===void 0?!1:c;Object.isExtensible(a);a=jc(a.g,b);a=a!==null?a:void 0;a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:c}function H(a,b,c){if(c!=null&&typeof c!=="boolean")throw Error("Expected boolean but got "+Ea(c)+": "+c);ic(a);var d=a.g;kc(d,d[E]|0,b,c===!1?void 0:c);return a};function nc(a,b,c){this.g=cc(a,b,c)}nc.prototype.toJSON=function(){var a=bc(this);return a};nc.prototype[Hb]=Tb;nc.prototype.toString=function(){return this.g.toString()};var I=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var oc=[],pc=[],qc=!1;function rc(a){oc[oc.length]=a;if(qc)for(var b=0;b<pc.length;b++)a(z(pc[b].g,pc[b]))};function J(){this.l=this.l;this.o=this.o}J.prototype.l=!1;J.prototype.isDisposed=function(){return this.l};J.prototype.dispose=function(){this.l||(this.l=!0,this.F())};J.prototype[Symbol.dispose]=function(){this.dispose()};J.prototype.F=function(){if(this.o)for(;this.o.length;)this.o.shift()()};function K(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1}K.prototype.h=function(){this.defaultPrevented=!0};function L(a,b){K.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.i=null;a&&this.init(a,b)}C(L,K);
L.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.i=a;a.defaultPrevented&&L.H.h.call(this)};L.prototype.h=function(){L.H.h.call(this);var a=this.i;a.preventDefault?a.preventDefault():a.returnValue=!1};var sc="closure_listenable_"+(Math.random()*1E6|0);var tc=0;function uc(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.P=e;this.key=++tc;this.L=this.N=!1}function vc(a){a.L=!0;a.listener=null;a.proxy=null;a.src=null;a.P=null};function wc(a){this.src=a;this.g={};this.h=0}wc.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.g[h];a||(a=this.g[h]=[],this.h++);var f=xc(a,b,d,e);f>-1?(b=a[f],c||(b.N=!1)):(b=new uc(b,this.src,h,!!d,e),b.N=c,a.push(b));return b};function yc(a,b){var c=b.type;c in a.g&&Qa(a.g[c],b)&&(vc(b),a.g[c].length==0&&(delete a.g[c],a.h--))}function xc(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.L&&h.listener==b&&h.capture==!!c&&h.P==d)return e}return-1};var zc="closure_lm_"+(Math.random()*1E6|0),Ac={},Bc=0;function Cc(a,b,c,d,e){if(Array.isArray(b))for(var h=0;h<b.length;h++)Cc(a,b[h],c,d,e);else(d=Ga(d)?!!d.capture:!!d,c=Dc(c),a&&a[sc])?(a=a.i,b=String(b).toString(),b in a.g&&(h=a.g[b],c=xc(h,c,d,e),c>-1&&(vc(h[c]),Array.prototype.splice.call(h,c,1),h.length==0&&(delete a.g[b],a.h--)))):a&&(a=Ec(a))&&(b=a.g[b.toString()],a=-1,b&&(a=xc(b,c,d,e)),(c=a>-1?b[a]:null)&&Fc(c))}
function Fc(a){if(typeof a!=="number"&&a&&!a.L){var b=a.src;if(b&&b[sc])yc(b.i,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(c in Ac?Ac[c]:Ac[c]="on"+c,d):b.addListener&&b.removeListener&&b.removeListener(d);Bc--;(c=Ec(b))?(yc(c,a),c.h==0&&(c.src=null,b[zc]=null)):vc(a)}}}function Gc(a,b){if(a.L)a=!0;else{b=new L(b,this);var c=a.listener,d=a.P||a.src;a.N&&Fc(a);a=c.call(d,b)}return a}
function Ec(a){a=a[zc];return a instanceof wc?a:null}var Hc="__closure_events_fn_"+(Math.random()*1E9>>>0);function Dc(a){if(typeof a==="function")return a;a[Hc]||(a[Hc]=function(b){return a.handleEvent(b)});return a[Hc]}rc(function(a){Gc=a(Gc)});function M(){J.call(this);this.i=new wc(this);this.Z=this;this.C=null}C(M,J);M.prototype[sc]=!0;M.prototype.removeEventListener=function(a,b,c,d){Cc(this,a,b,c,d)};
function N(a,b){var c=a.C;if(c){var d=[];for(var e=1;c;c=c.C)d.push(c),++e}a=a.Z;c=b.type||b;typeof b==="string"?b=new K(b,a):b instanceof K?b.target=b.target||a:(e=b,b=new K(c,a),Za(b,e));e=!0;var h;if(d)for(h=d.length-1;h>=0;h--){var f=b.g=d[h];e=Ic(f,c,!0,b)&&e}f=b.g=a;e=Ic(f,c,!0,b)&&e;e=Ic(f,c,!1,b)&&e;if(d)for(h=0;h<d.length;h++)f=b.g=d[h],e=Ic(f,c,!1,b)&&e}
M.prototype.F=function(){M.H.F.call(this);if(this.i){var a=this.i,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,vc(d[e]);delete a.g[c];a.h--}}this.C=null};function Ic(a,b,c,d){b=a.i.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var f=b[h];if(f&&!f.L&&f.capture==c){var g=f.listener,k=f.P||f.src;f.N&&yc(a.i,f);e=g.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};function Jc(a){try{return x.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function Kc(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};function Lc(){};var Mc;function Nc(){}C(Nc,Lc);Nc.prototype.g=function(){return new XMLHttpRequest};Mc=new Nc;var Oc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Pc(a){a=a.match(Oc)[1]||null;!a&&x.self&&x.self.location&&(a=x.self.location.protocol.slice(0,-1));return a?a.toLowerCase():""}
function Qc(a,b){if(!b)return a;var c=a.indexOf("#");c<0&&(c=a.length);var d=a.indexOf("?");if(d<0||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}function Rc(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)Rc(a,String(b[d]),c);else b!=null&&c.push(a+(b===""?"":"="+encodeURIComponent(String(b))))}function Sc(a,b){var c=[];for(b=b||0;b<a.length;b+=2)Rc(a[b],a[b+1],c);return c.join("&")}
function Tc(a){var b=[],c;for(c in a)Rc(c,a[c],b);return b.join("&")}function Uc(a,b){var c=arguments.length==2?Sc(arguments[1],0):Sc(arguments,1);return Qc(a,c)};function O(a){M.call(this);this.headers=new Map;this.T=a||null;this.h=!1;this.g=null;this.B="";this.j=this.A=this.m=this.v=!1;this.D=0;this.s=null;this.M="";this.I=!1}C(O,M);var Vc=/^https?$/i,Wc=["POST","PUT"],Xc=[];function Yc(a,b,c,d,e,h,f){var g=new O;Xc.push(g);b&&g.i.add("complete",b,!1,void 0,void 0);g.i.add("ready",g.aa,!0,void 0,void 0);h&&(g.D=Math.max(0,h));f&&(g.I=f);Zc(g,a,c,d,e)}n=O.prototype;n.aa=function(){this.dispose();Qa(Xc,this)};
function Zc(a,b,c,d,e){if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.B+"; newUri="+b);c=c?c.toUpperCase():"GET";a.B=b;a.v=!1;a.h=!0;a.g=a.T?a.T.g():Mc.g();a.g.onreadystatechange=I(z(a.V,a));try{a.A=!0,a.g.open(c,String(b),!0),a.A=!1}catch(g){$c(a);return}b=d||"";d=new Map(a.headers);if(e)if(Object.getPrototypeOf(e)===Object.prototype)for(var h in e)d.set(h,e[h]);else if(typeof e.keys==="function"&&typeof e.get==="function"){h=v(e.keys());for(var f=h.next();!f.done;f=
h.next())f=f.value,d.set(f,e.get(f))}else throw Error("Unknown input type for opt_headers: "+String(e));e=Array.from(d.keys()).find(function(g){return"content-type"==g.toLowerCase()});h=x.FormData&&b instanceof x.FormData;!(Na(Wc,c)>=0)||e||h||d.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");c=v(d);for(e=c.next();!e.done;e=c.next())d=v(e.value),e=d.next().value,d=d.next().value,a.g.setRequestHeader(e,d);a.M&&(a.g.responseType=a.M);"withCredentials"in a.g&&a.g.withCredentials!==
a.I&&(a.g.withCredentials=a.I);try{ad(a),a.D>0&&(a.s=setTimeout(a.R.bind(a),a.D)),a.m=!0,a.g.send(b),a.m=!1}catch(g){$c(a)}}n.R=function(){typeof Ba!="undefined"&&this.g&&(N(this,"timeout"),this.abort(8))};function $c(a){a.h=!1;a.g&&(a.j=!0,a.g.abort(),a.j=!1);bd(a);cd(a)}function bd(a){a.v||(a.v=!0,N(a,"complete"),N(a,"error"))}n.abort=function(){this.g&&this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1,N(this,"complete"),N(this,"abort"),cd(this))};
n.F=function(){this.g&&(this.h&&(this.h=!1,this.j=!0,this.g.abort(),this.j=!1),cd(this,!0));O.H.F.call(this)};n.V=function(){this.isDisposed()||(this.A||this.m||this.j?dd(this):this.S())};n.S=function(){dd(this)};
function dd(a){if(a.h&&typeof Ba!="undefined")if(a.m&&(a.g?a.g.readyState:0)==4)setTimeout(a.V.bind(a),0);else if(N(a,"readystatechange"),(a.g?a.g.readyState:0)==4){a.h=!1;try{try{var b=(a.g?a.g.readyState:0)>2?a.g.status:-1}catch(h){b=-1}var c;if(!(c=Kc(b))){var d;if(d=b===0){var e=Pc(String(a.B));d=!Vc.test(e)}c=d}c?(N(a,"complete"),N(a,"success")):bd(a)}finally{cd(a)}}}function cd(a,b){if(a.g){ad(a);var c=a.g;a.g=null;b||N(a,"ready");try{c.onreadystatechange=null}catch(d){}}}
function ad(a){a.s&&(clearTimeout(a.s),a.s=null)}n.isActive=function(){return!!this.g};rc(function(a){O.prototype.S=a(O.prototype.S)});function mc(a){this.g=cc(a)}u(mc,nc);n=mc.prototype;n.getEnableSsEngine=function(){return F(this,2)};n.getEnableAwr=function(){return F(this,3)};n.getAlohaAutoGaRollout=function(){return F(this,5)};n.getEnableConfigurator=function(){return F(this,6)};n.getEnableMweb=function(){return F(this,7)};n.getEnableCtlConsentCheckbox=function(){return F(this,8)};n.getEnableIframe=function(){return F(this,9)};function ed(){var a=new mc;a=H(a,5,!0);a=H(a,2,!0);a=H(a,4,!1);a=H(a,8,!0);return H(a,9,!0)}
n.getEnableScreenshotNudge=function(){return F(this,10)};n.getEnableWebStartupConfigEndpoint=function(){return F(this,11)};n.getEnableJunkNudge=function(){return F(this,12)};n.getEnableConfiguratorLocale=function(){return F(this,13)};n.getEnableTinyNoPointer=function(){return F(this,14)};n.getEnableSupportSessionLogging=function(){return F(this,15)};n.getEnableFileUploadForScreenshot=function(){return F(this,16)};n.getEnableDirectDeflectionForSingleCategory=function(){return F(this,17)};
n.getEnableImageSanitization=function(){return F(this,18)};n.getEnableAlohaBinarySplit=function(){return F(this,19)};n.getEnableDbFeedbackIntents=function(){return F(this,20)};n.getEnableMarkMandatoryFieldsWithRequired=function(){return F(this,21)};n.getEnableFeedbackCategoryCustomUi=function(){return F(this,22)};n.getEnableRealtimeCtl=function(){return F(this,23)};function fd(a){this.g=cc(a)}u(fd,nc);function gd(a){return hd.some(function(b){return b.test(a)})}var hd=[/https:\/\/sandbox\.google\.com\/tools\/feedback/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/inapp/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/tools\/feedback/,/https:\/\/.*\.googleusercontent\.com\/inapp/];var id="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");var jd=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_light_binary.js"]),kd=la(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);
function ld(a,b){var c;var d=(c=a.formContent)==null?void 0:c.locale;c=d==null?void 0:d.split("-")[0];d=d&&id.includes(d)?d:c&&id.includes(c)?c:void 0;d=(d!=null?d:"en").replaceAll("-","_").toLowerCase();var e;a=((e=a.initializationData)==null?0:e.useNightlyRelease)?"nightly":"live";var h;return(b==null?0:(h=b.getEnableAlohaBinarySplit)==null?0:h.call(b))?ob(jd,a):ob(kd,a,d)};var md,nd;function od(a,b,c,d){if(md)return md;var e=ld(a,d);return md=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=sb(document,"SCRIPT");ib(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+e.toString()))};c.body.appendChild(g)})}
function pd(a,b,c,d){if(nd)return nd;var e=ld(a,d);return nd=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=sb(document,"SCRIPT");ib(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+e.toString()))};c.body.appendChild(g)})}
function qd(a,b,c,d,e){e=e===void 0?!0:e;var h,f,g,k,l;return ya(function(m){switch(m.g){case 1:return h=Date.now(),ra(m,od(a,c,d,b),2);case 2:f=m.i;if(!(e||((k=a.initializationData)==null?0:k.useNightlyRelease)||((l=a.initializationData)==null?0:l.isLocalServer))){g=f.initializeFeedbackClient(a,h,b);m.g=3;break}return ra(m,f.initializeFeedbackClientAsync(a,h,b),4);case 4:g=m.i;case 3:return g.initiateAloha(),m.return(g)}})}
function rd(a,b,c,d){var e,h,f;return ya(function(g){if(g.g==1)return e=Date.now(),ra(g,pd(a,c,d.document,b),2);if(g.g!=3)return h=g.i,ra(g,h.initializeFeedbackClientAsync(a,e,b,d),3);f=g.i;f.initiateAloha();return g.return(f)})}
function sd(a,b,c){var d=!0;d=d===void 0?!0:d;var e,h,f,g,k,l,m,p,r,A;return ya(function(G){e=c||x;if((h=b)==null?0:(g=(f=h).getEnableAlohaBinarySplit)==null?0:g.call(f)){k=e;if(k.isFormOpened)throw l=Error("Form is either loading or already opened"),l.name="DuplicateFormError",l;k.isFormOpened=!0;a.callbacks=a.callbacks||{};m=a.callbacks.onClose||function(){};a.callbacks.onClose=function(y){k.isFormOpened=!1;m(y)};try{return G.return(rd(a,b,k,e))}catch(y){throw k.isFormOpened=!1,y;}}else{p=e;if(p.isFormOpened)throw r=
Error("Form is either loading or already opened"),r.name="DuplicateFormError",r;p.isFormOpened=!0;a.callbacks=a.callbacks||{};A=a.callbacks.onClose||function(){};a.callbacks.onClose=function(y){p.isFormOpened=!1;A(y)};try{return G.return(qd(a,b,p,e.document,d))}catch(y){throw p.isFormOpened=!1,y;}}G.g=0})};function td(a,b){return ya(function(c){return c.return(new Promise(function(d){var e=ud(b!=null?b:"")+"/aloha_form_properties?productId="+a;Yc(e,function(h){var f=h.target;h=null;try{var g=JSON,k=g.stringify;if(f.g){var l=f.g.responseText;l.indexOf(")]}'\n")==0&&(l=l.substring(5));b:{if(x.JSON)try{var m=x.JSON.parse(l);break b}catch(A){}m=Jc(l)}}else m=void 0;var p=k.call(g,m);if(p==null||p=="")h=new fd;else{var r=JSON.parse(p);if(!Array.isArray(r))throw Error("dnarr");Rb(r,32);h=new fd(r)}}catch(A){k=
new fd;m=ed();m=H(m,7,!0);m=H(m,10,!0);m=H(m,12,!0);m=H(m,13,!1);m=H(m,14,!0);m=H(m,15,!0);m=H(m,20,!1);p=mc;if(m!=null){if(!(m instanceof p))throw Error("Expected instanceof "+Xb(p)+" but got "+(m&&Xb(m.constructor)));}else m=void 0;ic(k);p=k.g;kc(p,p[E]|0,1,m);h=k}d(h)},"GET","",{},2E3,!0)}))})}function ud(a){return gd(a)?a:"https://www.google.com/tools/feedback"};function vd(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||x,e=d.document,h=a.nonce||hb(d.document);h&&!a.nonce&&(a.nonce=h);if(a.flow=="help"){var f=Da("document.location.href",d);!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;if(b&&JSON&&JSON.stringify){var g=JSON.stringify(b);(f=g.length<=1200)&&(a.psdJson=g)}f||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(f=d.GOOGLE_FEEDBACK_START)f.apply(d,
b);else{d=c+"/load.js?";for(var k in a)b=a[k],b==null||Ga(b)||(d+=encodeURIComponent(k)+"="+encodeURIComponent(b)+"&");a=e?new vb(ub(e)):Ma||(Ma=new vb);a=sb(a.g,"SCRIPT");h&&a.setAttribute("nonce",h);h=db(d);ib(a,h);e.body.appendChild(a)}}
function wd(a,b,c,d){var e,h;ya(function(f){e=c||x;var g=a.serverEnvironment==="DEV",k=c||x;k=a.nonce||hb(k.document);g={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket,triggerId:a.triggerId},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,Aa:void 0,defaultFormInputValues:void 0,
defaultFormInputValuesString:void 0,abuseLink:a.abuseLink,additionalDataConsent:a.additionalDataConsent},initializationData:{isLocalServer:g,nonce:k,useNightlyRelease:g,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,
enableAnonymousFeedback:a.enableAnonymousFeedback}};b&&(k=new Map(Object.entries(b)),g.extraData.productSpecificData=k);h=g;return ra(f,sd(h,d,e),0)})}
Ca("userfeedback.api.startFeedback",function(a,b,c){try{if(a.flow==="help"){var d=a.helpCenterPath.replace(/^\//,"");gb(c||window,"https://support.google.com/"+d)}else a.flow==="submit"?vd(a,b,c):td(a.productId,a.feedbackServerUri).then(function(e){var h=e.g,f=h[E]|0,g=lc(h,f);if(g!=null&&(f=h[E]|0,!Ub(e,f))){var k=g;var l=k.g,m=l[E]|0;k=Ub(k,m)?new k.constructor(fc(l,m,!1)):k;k!==g&&(hc(e)&&(h=e.g,f=h[E]|0),g=k,kc(h,f,1,g))}e=g;h=!nb||(e==null?void 0:e.getEnableMweb());f=!a.tinyNoPointer||(e==null?
void 0:e.getEnableTinyNoPointer());!e||e.getAlohaAutoGaRollout()&&h&&f?wd(a,b,c,e):vd(a,b,c)},function(e){e&&e.name!=="DuplicateFormError"&&vd(a,b,c)})}catch(e){wd(a,b,c,null)}});function xd(a,b){this.i=a;this.j=b;this.h=0;this.g=null}xd.prototype.get=function(){if(this.h>0){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function yd(a,b){a.j(b);a.h<100&&(a.h++,b.next=a.g,a.g=b)};rc(function(){});function zd(){this.h=this.g=null}zd.prototype.add=function(a,b){var c=Ad.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function Bd(){var a=Cd,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var Ad=new xd(function(){return new Dd},function(a){return a.reset()});function Dd(){this.next=this.scope=this.g=null}Dd.prototype.set=function(a,b){this.g=a;this.scope=b;this.next=null};Dd.prototype.reset=function(){this.next=this.scope=this.g=null};var Ed,Fd=!1,Cd=new zd;function Gd(a,b){Ed||Hd();Fd||(Ed(),Fd=!0);Cd.add(a,b)}function Hd(){var a=Promise.resolve(void 0);Ed=function(){a.then(Id)}}function Id(){for(var a;a=Bd();){try{a.g.call(a.scope)}catch(b){wb(b)}yd(Ad,a)}Fd=!1};function Jd(){};function Kd(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function P(a){this.g=0;this.o=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=Jd)try{var b=this;a.call(void 0,function(c){Q(b,2,c)},function(c){Q(b,3,c)})}catch(c){Q(this,3,c)}}function Ld(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1}Ld.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};var Md=new xd(function(){return new Ld},function(a){a.reset()});function Nd(a,b,c){var d=Md.get();d.j=a;d.h=b;d.i=c;return d}
function Od(a){if(a instanceof P)return a;var b=new P(Jd);Q(b,2,a);return b}function Pd(a,b,c){Qd(a,b,c,null)||Gd(B(b,a))}function Rd(a){return new P(function(b){var c=a.length,d=[];if(c)for(var e=function(g,k,l){c--;d[g]=k?{da:!0,value:l}:{da:!1,reason:l};c==0&&b(d)},h,f=0;f<a.length;f++)h=a[f],Pd(h,B(e,f,!0),B(e,f,!1));else b(d)})}P.prototype.then=function(a,b,c){return Sd(this,I(typeof a==="function"?a:null),I(typeof b==="function"?b:null),c)};P.prototype.$goog_Thenable=!0;
function Td(a,b){return Sd(a,null,I(b))}P.prototype.cancel=function(a){if(this.g==0){var b=new R(a);Gd(function(){Ud(this,b)},this)}};function Ud(a,b){if(a.g==0)if(a.i){var c=a.i;if(c.h){for(var d=0,e=null,h=null,f=c.h;f&&(f.l||(d++,f.g==a&&(e=f),!(e&&d>1)));f=f.next)e||(h=f);e&&(c.g==0&&d==1?Ud(c,b):(h?(d=h,d.next==c.j&&(c.j=d),d.next=d.next.next):Vd(c),Wd(c,e,3,b)))}a.i=null}else Q(a,3,b)}function Xd(a,b){a.h||a.g!=2&&a.g!=3||Yd(a);a.j?a.j.next=b:a.h=b;a.j=b}
function Sd(a,b,c,d){var e=Nd(null,null,null);e.g=new P(function(h,f){e.j=b?function(g){try{var k=b.call(d,g);h(k)}catch(l){f(l)}}:h;e.h=c?function(g){try{var k=c.call(d,g);k===void 0&&g instanceof R?f(g):h(k)}catch(l){f(l)}}:f});e.g.i=a;Xd(a,e);return e.g}P.prototype.v=function(a){this.g=0;Q(this,2,a)};P.prototype.A=function(a){this.g=0;Q(this,3,a)};
function Q(a,b,c){a.g==0&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.g=1,Qd(c,a.v,a.A,a)||(a.o=c,a.g=b,a.i=null,Yd(a),b!=3||c instanceof R||Zd(a,c)))}function Qd(a,b,c,d){if(a instanceof P)return Xd(a,Nd(b||Jd,c||null,d)),!0;if(Kd(a))return a.then(b,c,d),!0;if(Ga(a))try{var e=a.then;if(typeof e==="function")return $d(a,e,b,c,d),!0}catch(h){return c.call(d,h),!0}return!1}
function $d(a,b,c,d,e){function h(k){g||(g=!0,d.call(e,k))}function f(k){g||(g=!0,c.call(e,k))}var g=!1;try{b.call(a,f,h)}catch(k){h(k)}}function Yd(a){a.m||(a.m=!0,Gd(a.s,a))}function Vd(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b}P.prototype.s=function(){for(var a;a=Vd(this);)Wd(this,a,this.g,this.o);this.m=!1};
function Wd(a,b,c,d){if(c==3&&b.h&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,ae(b,c,d);else try{b.l?b.j.call(b.i):ae(b,c,d)}catch(e){be.call(null,e)}yd(Md,b)}function ae(a,b,c){b==2?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)}function Zd(a,b){a.l=!0;Gd(function(){a.l&&be.call(null,b)})}var be=wb;function R(a){D.call(this,a);this.g=!1}C(R,D);R.prototype.name="cancel";function ce(a){a=a===void 0?{}:a;this.useNotifications=a.useNotifications||!1;this.operatorDeferredUrl=a.operatorDeferredUrl;this.alphaTestMode=a.alphaTestMode||!1;this.stagingMode=a.stagingMode||!1;this.disableCustomerInitialization=a.disableCustomerInitialization||!1;this.rosterId=a.rosterId||"talk_roster";this.feedbackId=a.feedbackId||74772;this.moleVersion=a.moleVersion||void 0;this.gstaticBaseUrl=a.gstaticBaseUrl||void 0;this.operatorDeferredBaseUrl=a.operatorDeferredBaseUrl||void 0;this.forceLeftMoles=
a.forceLeftMoles||void 0;this.helpCenterName=a.helpCenterName||null;this.localeName=a.localeName||null;this.document=a.document||document;this.source=a.source||void 0;this.entityId=a.entityId||void 0;this.authUser=a.authUser||void 0;this.appDomain=a.appDomain||void 0;this.apiKey=a.apiKey||void 0;this.hideQueueWidget=a.hideQueueWidget||!1;this.hideMoles=a.hideMoles||!1;this.enableMinimizeRestoreKeyboardShortcut=a.enableMinimizeRestoreKeyboardShortcut||!1;this.showSecondsInChatTranscript=a.showSecondsInChatTranscript||
!1;this.settings=a.settings||void 0;this.jsHint=a.jsHint||void 0;this.xhrTimeoutMs=a.xhrTimeoutMs||3E4;this.enableChatSmartReply=a.enableChatSmartReply||!1;this.isCasesHostPage=a.isCasesHostPage||!1};/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
function S(a){var b=de;this.l=[];this.C=b;this.B=a||null;this.j=this.i=!1;this.h=void 0;this.v=this.D=this.o=!1;this.m=0;this.g=null;this.s=0}S.prototype.cancel=function(a){if(this.i)this.h instanceof S&&this.h.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.s--,b.s<=0&&b.cancel())}this.C?this.C.call(this.B,this):this.v=!0;this.i||(a=new ee(this),fe(this),ge(this,!1,a))}};S.prototype.A=function(a,b){this.o=!1;ge(this,a,b)};function ge(a,b,c){a.i=!0;a.h=c;a.j=!b;he(a)}
function fe(a){if(a.i){if(!a.v)throw new ie(a);a.v=!1}}S.prototype.callback=function(a){fe(this);ge(this,!0,a)};function je(a,b,c,d){var e=a.i;e||(b===c?b=c=I(b):(b=I(b),c=I(c)));a.l.push([b,c,d]);e&&he(a)}S.prototype.then=function(a,b,c){var d,e,h=new P(function(f,g){e=f;d=g});je(this,e,function(f){f instanceof ee?h.cancel():d(f);return ke},this);return h.then(a,b,c)};S.prototype.$goog_Thenable=!0;function le(a){return Pa(a.l,function(b){return typeof b[1]==="function"})}var ke={};
function he(a){if(a.m&&a.i&&le(a)){var b=a.m,c=me[b];c&&(x.clearTimeout(c.g),delete me[b]);a.m=0}a.g&&(a.g.s--,delete a.g);b=a.h;for(var d=c=!1;a.l.length&&!a.o;){var e=a.l.shift(),h=e[0],f=e[1];e=e[2];if(h=a.j?f:h)try{var g=h.call(e||a.B,b);g===ke&&(g=void 0);g!==void 0&&(a.j=a.j&&(g==b||g instanceof Error),a.h=b=g);if(Kd(b)||typeof x.Promise==="function"&&b instanceof x.Promise)d=!0,a.o=!0}catch(k){b=k,a.j=!0,le(a)||(c=!0)}}a.h=b;d&&(g=z(a.A,a,!0),d=z(a.A,a,!1),b instanceof S?(je(b,g,d),b.D=!0):
b.then(g,d));c&&(b=new ne(b),me[b.g]=b,a.m=b.g)}function ie(){D.call(this)}C(ie,D);ie.prototype.message="Deferred has already fired";ie.prototype.name="AlreadyCalledError";function ee(){D.call(this)}C(ee,D);ee.prototype.message="Deferred was canceled";ee.prototype.name="CanceledError";function ne(a){this.g=x.setTimeout(z(this.i,this),0);this.h=a}ne.prototype.i=function(){delete me[this.g];throw this.h;};var me={};function oe(a,b){var c=b||{};b=c.document||document;var d=eb(a).toString(),e=sb((new vb(b)).g,"SCRIPT"),h={W:e,R:void 0},f=new S(h),g=null,k=c.timeout!=null?c.timeout:5E3;k>0&&(g=window.setTimeout(function(){pe(e,!0);var l=new qe(1,"Timeout reached for loading script "+d);fe(f);ge(f,!1,l)},k),h.R=g);e.onload=e.onreadystatechange=function(){e.readyState&&e.readyState!="loaded"&&e.readyState!="complete"||(pe(e,c.ya||!1,g),f.callback(null))};e.onerror=function(){pe(e,!0,g);var l=new qe(0,"Error while loading script "+
d);fe(f);ge(f,!1,l)};h=c.attributes||{};Za(h,{type:"text/javascript",charset:"UTF-8"});pb(e,h);ib(e,a);re(b).appendChild(e);return f}function re(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&b.length!==0?b[0]:a.documentElement}function de(){if(this&&this.W){var a=this.W;a&&a.tagName=="SCRIPT"&&pe(a,!0,this.R)}}
function pe(a,b,c){c!=null&&x.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function qe(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);D.call(this,c);this.code=a}C(qe,D);function se(a,b){return te(a,b).then(function(c){var d=c.responseText;b&&b.ja&&(c=b.ja,d.lastIndexOf(c,0)==0&&(d=d.substring(c.length)));return JSON.parse(d)})}
function te(a,b){var c=b||{},d=c.Y?c.Y.g():Mc.g();return Td(new P(function(e,h){var f;try{d.open("GET",a,!0)}catch(l){h(new T("Error opening XHR: "+l.message,a,d))}d.onreadystatechange=function(){if(d.readyState==4){x.clearTimeout(f);var l;!(l=Kc(d.status))&&(l=d.status===0)&&(l=Pc(a),l=!(l=="http"||l=="https"||l==""));l?e(d):h(new ue(d.status,a,d))}};d.onerror=function(){h(new T("Network error",a,d))};if(c.headers)for(var g in c.headers){var k=c.headers[g];k!=null&&d.setRequestHeader(g,k)}c.withCredentials&&
(d.withCredentials=c.withCredentials);c.responseType&&(d.responseType=c.responseType);c.mimeType&&d.overrideMimeType(c.mimeType);c.X>0&&(f=x.setTimeout(function(){d.onreadystatechange=function(){};d.abort();h(new ve(a,d))},c.X));try{d.send(null)}catch(l){d.onreadystatechange=function(){},x.clearTimeout(f),h(new T("Error sending XHR: "+l.message,a,d))}}),function(e){e instanceof R&&d.abort();throw e;})}function T(a,b){D.call(this,a+", url="+b);this.url=b}C(T,D);T.prototype.name="XhrError";
function ue(a,b,c){T.call(this,"Request Failed, status="+a,b,c);this.status=a}C(ue,T);ue.prototype.name="XhrHttpError";function ve(a,b){T.call(this,"Request timed out",a,b)}C(ve,T);ve.prototype.name="XhrTimeoutError";function we(){}C(we,Lc);we.prototype.g=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if(typeof XDomainRequest!="undefined")return new xe;throw Error("Unsupported browser");};function xe(){this.g=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText="";this.status=-1;this.statusText="";this.g.onload=z(this.ea,this);this.g.onerror=z(this.U,this);this.g.onprogress=z(this.fa,this);this.g.ontimeout=z(this.ga,this)}n=xe.prototype;
n.open=function(a,b,c){if(c!=null&&!c)throw Error("Only async requests are supported.");this.g.open(a,b)};n.send=function(a){if(a)if(typeof a=="string")this.g.send(a);else throw Error("Only string data is supported");else this.g.send()};n.abort=function(){this.g.abort()};n.setRequestHeader=function(){};n.getResponseHeader=function(a){return a.toLowerCase()=="content-type"?this.g.contentType:""};n.ea=function(){this.status=200;this.responseText=this.g.responseText;ye(this,4)};
n.U=function(){this.status=500;this.responseText="";ye(this,4)};n.ga=function(){this.U()};n.fa=function(){this.status=200;ye(this,1)};function ye(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}n.getAllResponseHeaders=function(){return"content-type: "+this.g.contentType};function ze(a){this.config=a instanceof ce?a:new ce(a);this.config=Ae(this.config);this.g=Be(this);this.i=this.config.moleVersion?Od():this.g.then(function(b){this.config.moleVersion=b.cbfVersion;this.config.screenShareVersion=b.screenShareVersion},function(){},this);this.j=this.g.then(function(b){this.config.settings=this.config.settings?Object.assign({},b.settings,this.config.settings):b.settings},function(){},this);this.g.then(this.h,function(){},this)}
function Be(a){return se(a.config.alphaTestMode?"//ssl.gstatic.com/support/realtime/operatorParamsDev":a.config.stagingMode?"//ssl.gstatic.com/support/realtime/operatorParamsStaging":"//ssl.gstatic.com/support/realtime/operatorParams",{X:a.config.xhrTimeoutMs,Y:new we}).then(function(b){if(!b)throw Error("operatorParams is null");return b},function(b){throw b;})}
function Ce(a){var b=De();if(b)return b;if(b=Da("cs.operatorDeferredInstance"))return b=Od(b),Ee(b),b;b=Rd([a.i,a.j]).then(function(){return Fe(a).then(function(c){var d={document:this.config.document,timeout:this.config.xhrTimeoutMs};this.config.operatorDeferredUrl=c;try{return oe(db(c===null?"null":c===void 0?"undefined":c),d).then(function(){return x.cs.OperatorDeferred.getInstance(this.config)},function(e){throw e;},this)}catch(e){throw e;}},null,a)},function(){},a);Ee(b);return b}
ze.prototype.h=function(a){(new RegExp(a.eagerLoadHostnamePattern,a.eagerLoadHostnameFlags)).test(this.config.document.location.href)&&Td(Ce(this),B(Ge,"Error retrieving OperatorDeferred"))};
function Fe(a){return a.config.operatorDeferredUrl?Od(a.config.operatorDeferredUrl):a.config.operatorDeferredBaseUrl?(a=a.config.operatorDeferredBaseUrl+"/"+a.config.moleVersion+"/operatordeferred_bin_base__"+a.config.localeName.replace(/-/g,"_").toLowerCase()+".js",Od(a)):a.g.then(z(function(b){return"https://ssl.gstatic.com/support/realtime/operator/"+b.cbfVersion+"/operatordeferred_bin_base__"+this.config.localeName.replace(/-/g,"_").toLowerCase()+".js"},a),function(b){throw b;})}
function He(a,b){return Ce(a).then(B(function(c,d){d.registerAvailabilityCallbacks(c)},b))}ze.prototype.K=function(){return Ce(this).then(function(a){a.ensureSubscribed()})};function De(){var a=Da("cs.operatorDeferredPromise");return a instanceof P?a:a!=null?Od(a):null}function Ee(a){Ca("cs.operatorDeferredPromise",a)}function Ge(){}
function Ae(a){a=Xa(a);a.document=a.document||document;a.localeName!=null&&(a.localeName=a.localeName.replace(/_/g,"-"));a.localeName=a.localeName&&Na(Ie,a.localeName)>=0?a.localeName:"en";a.helpCenterName=a.helpCenterName||"chatsupport";a.apiKey=a.apiKey||"AIzaSyB5V4SIBGmrqREm7kf2fBJgPcBMCdUrLzE";return a}var Ie="af am ar ar-XB bg bn ca cs da de el en en-AU en-GB en-XA en-XC es es-419 et eu fa fi fil fr gl gu hi hr hu id is it iw ja kn ko lt lv ml mr ms nl no pl pt-PT pt-BR ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW zh-HK zu".split(" ");function Je(a){ze.call(this,a)}u(Je,ze);function Ke(a){J.call(this);this.h=a}C(Ke,J);Ke.prototype.g=function(a){return Le(this,a)};function U(a,b){a=Object.prototype.hasOwnProperty.call(a,Ha)&&a[Ha]||(a[Ha]=++Ia);return(b?"__wrapper_":"__protected_")+a+"__"}function Le(a,b){var c=U(a,!0);b[c]||((b[c]=Me(a,b))[U(a,!1)]=b);return b[c]}
function Me(a,b){function c(){if(a.isDisposed())return b.apply(this,arguments);try{return b.apply(this,arguments)}catch(e){var d=e;if(!(d&&typeof d==="object"&&typeof d.message==="string"&&d.message.indexOf("Error in protected function: ")==0||typeof d==="string"&&d.indexOf("Error in protected function: ")==0))throw a.h(d),new Ne(d);}}c[U(a,!1)]=b;return c}
function Oe(a,b){var c=x.window||x.globalThis,d=c[b];if(!d)throw Error(b+" not on global?");c[b]=function(e,h){typeof e==="string"&&(e=B(La,e));e&&(arguments[0]=e=Le(a,e));if(d.apply)return d.apply(this,arguments);var f=e;if(arguments.length>2){var g=Array.prototype.slice.call(arguments,2);f=function(){e.apply(this,g)}}return d(f,h)};c[b][U(a,!1)]=d}
Ke.prototype.F=function(){var a=x.window||x.globalThis;var b=a.setTimeout;b=b[U(this,!1)]||b;a.setTimeout=b;b=a.setInterval;b=b[U(this,!1)]||b;a.setInterval=b;Ke.H.F.call(this)};function Ne(a){D.call(this,"Error in protected function: "+(a&&a.message?String(a.message):String(a)),a);(a=a&&a.stack)&&typeof a==="string"&&(this.stack=a)}C(Ne,D);function Pe(a,b,c){M.call(this);this.j=b||null;this.h={};this.v=Qe;this.s=a;if(!c){this.g=null;this.g=new Ke(z(this.m,this));Oe(this.g,"setTimeout");Oe(this.g,"setInterval");a=this.g;b=x.window||x.globalThis;c=["requestAnimationFrame","mozRequestAnimationFrame","webkitAnimationFrame","msRequestAnimationFrame"];for(var d=0;d<c.length;d++){var e=c[d];c[d]in b&&Oe(a,e)}a=this.g;qc=!0;b=z(a.g,a);for(c=0;c<oc.length;c++)oc[c](b);pc.push(a)}}C(Pe,M);function Re(a){K.call(this,"a");this.error=a}C(Re,K);
function Qe(a,b,c,d){if(d instanceof Map){var e={};d=v(d);for(var h=d.next();!h.done;h=d.next()){var f=v(h.value);h=f.next().value;f=f.next().value;e[h]=f}}else e=d;Yc(a,null,b,c,e)}
Pe.prototype.m=function(a,b){a=a.error||a;b=b?Xa(b):{};a instanceof Error&&Za(b,a.__closure__error__context__984382||{});var c=Sa(a);if(this.j)try{this.j(c,b)}catch(r){}var d=c.message.substring(0,1900);if(!(a instanceof D)||a.g){var e=c.fileName,h=c.lineNumber;a=c.stack;try{var f=Uc(this.s,"script",e,"error",d,"line",h);a:{for(var g in this.h){var k=!1;break a}k=!0}if(!k){k=f;var l=Tc(this.h);f=Qc(k,l)}l={};l.trace=a;if(b)for(var m in b)l["context."+m]=b[m];var p=Tc(l);this.v(f,"POST",p,this.A)}catch(r){}}try{N(this,
new Re(c,b))}catch(r){}};Pe.prototype.F=function(){var a=this.g;a&&typeof a.dispose=="function"&&a.dispose();Pe.H.F.call(this)};function V(a,b,c,d,e,h){var f=new Pe("//www.google.com/tools/feedback/jserror",void 0,!0);this.l=z(f.m,f);this.v=a;this.B=c||"en";this.A=b||!1;this.D=!!d;this.s=e;this.i=this.g=null;this.o=h}
function Se(a,b,c,d,e,h){if(Te())return null;window.top.GOOGLE_HELP_CHAT_OPERATOR_V2=Je;if(window.top.GOOGLE_HELP_CHAT_SUPPORT)return null;a=new V(a,b,c,d,e,h);window.top.GOOGLE_HELP_CHAT_SUPPORT=a;Ue(a);window.addEventListener("message",function(f){f.data==="helpPanelEnsureSubscribed"&&Ve.test(f.origin)&&(window.top.GOOGLE_HELP_CHAT_SUPPORT.K(),console.log("Chat ensureSubscribed called by HP event listener."))});return a}
function Te(){var a=window;try{return a==null||a.top==null||a.top.document==null}catch(b){return!0}}function Ue(a){var b={helpCenterName:a.v,localeName:a.B,source:1,rosterId:"roster-for-Google-Help",isRtl:a.A,alphaTestMode:!1,stagingMode:a.D,timeoutMs:2E4,authUser:a.s,apiKey:a.o},c=rb("DIV",{id:"roster-for-Google-Help",style:"display: none"});window.top.document.body.appendChild(c);try{a.j=new Je(b)}catch(d){a.l(d)}}function We(a,b,c){if(b!=null&&c!=null){var d={};d[b]=c;Td(He(a.j,d),a.l)}}
V.prototype.m=function(a){this.g=a;We(this,this.g,this.h)};V.prototype.C=function(a){this.h=a;We(this,this.g,this.h)};V.prototype.K=function(){this.j.K()};var Ve=new RegExp(/^https:\/\/(pay.*|billing-ads-qa-devel|daily-1|dasher-workspace-*|madden.*|meet-dev|orderfood-autopush|orderfood-staging|gpay-landing.*|spot.*|subscribe-qual|tokenized.*)?\.?(bpui0|corp|developers|food|maps|meet|news|orderfood|payments|pay|play|sandbox|workspace|www)\.(google|youtube|admob)\.\w+\.?\w*/);
V.prototype.setChatPool=V.prototype.m;V.prototype.setChatCallback=V.prototype.C;V.prototype.ensureSubscribed=V.prototype.K;function Xe(){}Xe.prototype.next=function(){return Ye};var Ye={done:!0,value:void 0};Xe.prototype.J=function(){return this};function Ze(a){if(a instanceof W||a instanceof X||a instanceof Y)return a;if(typeof a.next=="function")return new W(function(){return a});if(typeof a[Symbol.iterator]=="function")return new W(function(){return a[Symbol.iterator]()});if(typeof a.J=="function")return new W(function(){return a.J()});throw Error("Not an iterator or iterable.");}function W(a){this.g=a}W.prototype.J=function(){return new X(this.g())};W.prototype[Symbol.iterator]=function(){return new Y(this.g())};W.prototype.h=function(){return new Y(this.g())};
function X(a){this.g=a}u(X,Xe);X.prototype.next=function(){return this.g.next()};X.prototype[Symbol.iterator]=function(){return new Y(this.g)};X.prototype.h=function(){return new Y(this.g)};function Y(a){W.call(this,function(){return a});this.i=a}u(Y,W);Y.prototype.next=function(){return this.i.next()};function $e(){};function af(){}C(af,$e);af.prototype[Symbol.iterator]=function(){return Ze(this.J(!0)).h()};af.prototype.clear=function(){var a=Array.from(this);a=v(a);for(var b=a.next();!b.done;b=a.next())b=b.value,Z(this),this.g.removeItem(b)};function bf(a){this.g=a;this.h=null}C(bf,af);function cf(a){if(!jb||a.h===null){var b=a.g;if(b)try{b.setItem("__sak","1");b.removeItem("__sak");var c=!0}catch(d){c=d instanceof DOMException&&(d.name==="QuotaExceededError"||d.code===22||d.code===1014||d.name==="NS_ERROR_DOM_QUOTA_REACHED")&&b&&b.length!==0}else c=!1;a.h=c}return a.h}n=bf.prototype;
n.set=function(a,b){Z(this);try{this.g.setItem(a,b)}catch(c){if(this.g.length==0)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};n.get=function(a){Z(this);a=this.g.getItem(a);if(typeof a!=="string"&&a!==null)throw"Storage mechanism: Invalid value was encountered";return a};
n.J=function(a){Z(this);var b=0,c=this.g,d=new Xe;d.next=function(){if(b>=c.length)return Ye;var e=c.key(b++);if(a)return{value:e,done:!1};e=c.getItem(e);if(typeof e!=="string")throw"Storage mechanism: Invalid value was encountered";return{value:e,done:!1}};return d};n.clear=function(){Z(this);this.g.clear()};n.key=function(a){Z(this);return this.g.key(a)};
function Z(a){if(a.g==null)throw Error("Storage mechanism: Storage unavailable");var b;(jb?cf(a):(b=a.h)!=null?b:cf(a))||wb(Error("Storage mechanism: Storage unavailable"))};function df(){var a=null;try{a=x.sessionStorage||null}catch(b){}bf.call(this,a)}C(df,bf);function ef(){J.call(this);this.g=new df}u(ef,J);ef.prototype.clear=function(){var a=this.g;Z(a);a.g.removeItem("GOOGLE_HELP_SESSION_STATE")};(function(a){var b=a.helpCenterPath,c=a.locale,d=a.authuser,e=a.escalationJSONString,h=!!a.useStagingServer;a=a.apiKey;var f=document.body;a:{var g=ub(f);if(g.defaultView&&g.defaultView.getComputedStyle&&(g=g.defaultView.getComputedStyle(f,null))){g=g.direction||g.getPropertyValue("direction")||"";break a}g=""}b=Se(b,"rtl"==(g||(f.currentStyle?f.currentStyle.direction:null)||f.style&&f.style.direction),c,h,d,a);c=new ef;e&&(c.clear(),e={ba:JSON.parse(e).ba},e.sessionTimestamp=(new Date).getTime(),
c.g.set("GOOGLE_HELP_SESSION_STATE",JSON.stringify(e)));if(e=c.g.get("GOOGLE_HELP_SESSION_STATE")){if(e=JSON.parse(e),d=(new Date).getTime(),h=e.sessionTimestamp,!h||typeof h!=="number"||d>h+6E4)c.clear(),e=null}else e=null;c=(e||{}).escalationOptions;if(b&&c){e=c.hangout||{};(c=(c.chat||{}).chat_pool_id)&&b.m(c);if(e=e.hangout_pool_id)b.i=e,We(b,b.i,b.I);b.K()}}).apply(x,x.GOOGLE_HELP_CHAT_ARGUMENTS);}).call(this);
