var __IntegralASDiagnosticCall = (function(code, err, config) {
	try {
		var alreadySent = false;
		return function(code, err, config) {
			try {
				if (!alreadySent) {
					alreadySent = true;
					if (config) {
						// cannot stringify DOM node due to parent-child relationship
						config.contextNode = '';
					}
	
					var img = new Image();
					img.src = '//fw.adsafeprotected.com/jsdiagnostic' +
						'?code:' + code +
						'&err:' + encodeURIComponent(err.message) +
						'&config:' + encodeURIComponent(JSON.stringify(config));
				}
			} catch(err) {}
		};
	} catch(err) {
		return function(){};
	}
})();

try {
	var __IntegralASConfig = {
		jsDoSplit : "false",
		cocaPuffsPath : "",
		debug : "false",
		killPhrases : "",
		useAdTalk : "true",
		jsDiag:'true',
		version:'0',
		mtCell: 10,
		mtSample: 5,
		cookieDomain:'sc.iasds01.com/dtc',
		trackMouse : "true",
		exchList:{'e1':'nqzryq','e2':'tbbtyrnqf.t.qbhoyrpyvpx','e3':'ehovpbacebwrpg','e4':'chozngvp','e5':'bcrak','e6':'nqoevgr.pbz','e7':'tynz.pbz','e8':'lvryqznantre.pbz','e9':'yvwvg','e10':'nqakf','p11':'ghea.pbz','p12':'zngugnt','p13':'vaivgrzrqvn','p14':'qngnkh','n15':'zrqvn6qrterrf','n16':'dhnagfreir','n17':'esvuho.arg','a18':'napubeserr','a19':'eff2frnepu','a20':'mgfgngvp.pbz','n21':'ovq.npr.nqiregvfvat','e22':'wnfba','v23':'fcbgkpqa','v24':'ogeyy','v25':'yvirenvy','v26':'nqncgi','v27':'nqnc.gi','n29':'qbzqrk.pbz','n30':'ernyih.arg','d31':'cvengronl','d32':'cebklonl','d33':'onlcebkl','d34':'cvengrcebkl','d35':'cebklcvengr','d36':'onlcvengr','n37':'tjnyyrg','p39':'j55p.arg','p40':'c0l.pa'},
		protocol:'https',
		jsref : "",
		asid : "52af0174-cf67-11e5-a4c4-0025904ea178",
		allowViewability : "true",
		jsFeatures : "mousetrack,cocoapuffs,viewabilityready,consecutive,cachebust:0,forcecocoa:100,rattie:0,exch,recordalternate:0,usedtdomain,nextcocoa:100,bapiDiag,cookie,postDts:0,unreliabilityDetection,videotwoseconds,getPl,decodePl,resolution,usetpl,usesca:1,tpiLookupURL,hundredpct,jloadDiag:0,cdnTest:1,blur,sendclogs,zeroPing,idMap,offscreen,everySecond:1,sdkdetection,moreAdTalkCalls,slid,fm2:1,largeAd,nextcocoaie:100,usevh,mraidinjection",
		adTalkDtCall : "true",
		adsafeDomain : "adsafeprotected.com:80",
		minimizeCalls : "false",
		adWidth : "300",
		adHeight : "250",
		forceAppend : "false",
		mode : "jss",
		_onInViewMRC15 : __IntegralASConfig && __IntegralASConfig.onInViewMRC15,
		_onAPIResult : __IntegralASConfig && __IntegralASConfig.onAPIResult,
		_onMeasurable : __IntegralASConfig && __IntegralASConfig.onMeasurable,
		_onSuspicious : __IntegralASConfig && __IntegralASConfig.onSuspicious,
		_onInViewMRC : __IntegralASConfig && __IntegralASConfig.onInViewMRC,
		_onInViewMRC5 : __IntegralASConfig && __IntegralASConfig.onInViewMRC5,
		requrl : "",
		reqquery : "",
		dtBaseURL: "https:\/\/dt.adsafeprotected.com\/dt",
		adsafeSrc : "https:\/\/pixel.adsafeprotected.com\/rfw\/st\/33642\/3584127\/skeleton.js",
		adsafeSep : "?",
		tpiLookupURL:"",
		getTpl: "false",
		use100v: true,
		useBapiCallback: "",
		useViewabilityNotification: "",
		scriptUrl : "https://pixel.adsafeprotected.com/rjss/st/33642/3584127/skeleton.js",
		accountForSadImps:'',
		sendCookie:'true',
		fwMonitoring:'true',
		cdnTestUrl: "//cdn.adsafeprotected.com/cdn-test.js",
		colloTestUrl: "//pixel.adsafeprotected.com/jload?campId=cdnTest&anId=100",
		doNothing: false,
		cdnTestEnabled: false,
		mn: "app04",
		cdnTestEnabled: false,
		mobOrTab: false,
		mobFwUrl : "https://mobile.adsafeprotected.com/internal/monitoring/app/initial/33642/3584127/",
		videoId : ''
	};

	if (__IntegralASConfig.jsFeatures.indexOf('asidJsDiagnostic') !== -1) {
		var fakeErr = { message: __IntegralASConfig.asid };
		__IntegralASDiagnosticCall('asid', fakeErr);
	}

	__IntegralASConfig.birthdate = new Date().getTime();
	__IntegralASConfig.useFIF = (!!window.__IntegralASUseFIF) && __IntegralASConfig.mode === 'jload';
	__IntegralASConfig.contextNode = (function() {
		if (__IntegralASConfig.useFIF) {
			return window.frameElement; // Early exit if using FIF
		}
		var tempScript,
			embedded = window != top,
			scripts = document.getElementsByTagName('script'),
			result = scripts[scripts.length - 1],
			scriptIndex = scripts.length,
			useDocWrite = 'jss,jsi,jspix'.indexOf(__IntegralASConfig.mode) !== -1,
			scriptUrl = __IntegralASConfig.scriptUrl;

		try {
			while (--scriptIndex >= 0) {
				tempScript = scripts[scriptIndex];
				if (tempScript.src && tempScript.src.indexOf(scriptUrl) === 0 && tempScript.getAttribute('data-ias-script-tag') === null) {
					result = tempScript;
					tempScript.setAttribute('data-ias-script-tag', 'found');
					break;
				}
			}
			if (scriptIndex === 0 && useDocWrite && !embedded) {
				document.write('<span id="s' + __IntegralASConfig.asid + '"/>');
				result = document.getElementById('s' + __IntegralASConfig.asid).parentNode;
			}
		} catch(e) { }
	
		return result;
	}());

} catch(err) {
	__IntegralASConfig = {};
	__IntegralASDiagnosticCall('bootstrapper', err);
}

__IntegralASConfig.initialize=function(l,t,x){var r,Xa=function(){r=new S;var a;r.provide("mobileApp",function(){return a=a||new la(g)});var c,d,b,f,g=ma(),m=na(g),k=oa(),q=pa(r),n=qa(),p=new ra(r),u=r.provide("mPage",sa()),C=ta(),y=ua(),v=va(),D=wa(n,v),v=xa(n),E=ya(n),z=za(),G=Aa(),t=Ba(z),J=Ca(z),N=w.isVideo()?Da(l.videoId,g,y):{},G=Ea(G,n,J,t,N,g),x=Fa(G,n,u),A=Ga(q),k=Ha(G,n,g,E,p,z,y,k),P=Ia(n,g,r,q),q=Ja(D,k,n,E,p),B=Ka(D,k),P=La(P,g),I=Ma(z,k,n,g,J,r,E,t,p,A,u,x,y,N),u=Na(D,n,g,E,P,p,z,I),
y=Oa(r),D=Pa(r),E=Qa(z,E,I);k.setViewabilityMod(I);var F;if(!function(){var a=!1,b,d;try{e.isDef(l)&&e.isDef(l.killPhrases)&&""!==l.killPhrases&&(b=l.adsafeSrc?l.adsafeSrc:l.requrl+l.reqquery,d=l.killPhrases.split(","),e(d).each(function(c,f){f=decodeURIComponent(d[c]).replace(/^\s+|\s+$/g,"");-1!==b.search(f)&&(a=!0)})),l.doNothing&&(a=!0)}catch(c){n.add(h.ERROR_CODES.KILL_IT)}return a}()){if(m.isApplicable())try{m.start(),p.addItem(m.getFrameMap(),"fm"),g.on("fm2")&&p.addItem(m.getFrameMapIncludingPeerCase(),
"fm2"),g.on("idMap")&&(c=m.getIdMap())&&p.addItem(c,"idMap")}catch(X){n.add(h.ERROR_CODES.ADTALK_GENERAL)}var K;try{"true"!==l.minimizeCalls&&I.init();g.on("mousetrack")&&(f=Ra(G,p),f.init());K=C.detectTopURL();g.on("exch")&&(d=Sa(n,p),d.parse(K));if(g.on("getPl")&&navigator&&navigator.plugins){b=Ta(navigator.plugins);var Q=b.hash();p.addItem({output:Q.join(".")},"pl",{type:h.DT_CODES.ADTALK});if(g.on("decodePl")&&Q.length){var R=b.decode(Q);p.addItem({output:R.join(".")},"pd",{type:h.DT_CODES.ADTALK})}}var L=
v.getProps();e(L).each(function(a,b){p.addItem({output:b},a,{type:"UFO"})})}catch(V){n.add(h.ERROR_CODES.IMPRESSION_LEADUP)}g.bootstrapOn("use100v")&&Ua();k.sendCookie();u.send(K);g.on("cdnTest")&&l.cdnTestEnabled&&D.init();E.isApplicable(g)&&E.start();g.bootstrapOn("getTpl")&&g.on("usetpl")&&q.init();l.tpiLookupURL&&B.init(l.tpiLookupURL);Va(g);"true"!==l.minimizeCalls&&(F=(new Date).getTime(),s.execAtEndOfThread(function(){s.execAtEndOfThread(function(){var a={output:(new Date).getTime()-F};p.addItem(a,
"sinceFw",{type:h.DT_CODES.ADTALK});e.isDef(I.readyFired())&&p.addItem({output:I.readyFired()},"readyFired",{type:h.DT_CODES.ADTALK});m.sendAdTalkCall()})}));g.on("usesca")&&y.load()}g.on("usevh")&&Wa()},e=function(a){var c=function(b){var c=null===a,c="object"===typeof a&&!c,f=!d()&&c;return b?c:f},d=function(){return a instanceof Array},b=function(b,d){if(a.length===+a.length)for(var c=0,f=a.length;c<f;++c)b(c,a[c]);else for(c in a)(a.hasOwnProperty(c)||d)&&b(c,a[c])},f=function(a,d){var c=[];b(function(b,
f){var g=a(b,f);if(void 0!==g||d)c[c.length]=g});return c},g=function(a,d){d=d||",";var c=[];b(function(b,d){var f=a(b,d);e.isDef(f)&&c.push(f)});return c.join(d)},m=function(a,b,d){for(var c in b)e.isDef(b[c])&&(d||b.hasOwnProperty(c))&&(a[c]=b[c]);return a},k=function(a){var d={};b(function(b,f){var g=a(b,f);c(g)&&m(d,g)});return d};return{each:b,isObj:c,isArray:d,invert:function(){return k(function(a,b){var d={};d[b]=a;return d})},mapToObj:k,map:f,keys:function(){var a=[];b(function(b){a.push(b)});
return a},toParams:function(a){return g(function(a,b){return"string"===typeof a&&-1!==a.indexOf("NULL")?b:a+":"+b},a)},stringify:g,toION:function(b,g){var k,m="[",C="]";g=g||0;b=b||{};if(4<++g)return"object";if(!c(!0))return a;d()?k=f(function(a,d){return e(d).toION(b,g)}):(m="{",C="}",k=f(function(a,d){return(b[a]||a)+":"+e(d).toION(b,g)}));return m+k.join(",")+C},compareTo:function(a){var d=!1;b(function(b,c){a[b]!==c&&(d||(d={}),d[b]=c)});return d},mixin:function(b,d){return m(a,b,d)},find:function(a){var d;
b(function(b,c){a(b,c)&&(d=c)});return d},findFirst:function(a){var d,c;b(function(b,f){!c&&a(b,f)&&(d=f,c=!0)});return d},asStrings:function(){var a={};b(function(b,d){a[b]=""+d});return a},selectProperties:function(b){var d={};e(b).each(function(b,c){e.isDef(a[c])&&(d[c]=a[c])});return d},filter:function(a,b){return f(function(b,d){var c;if(e.isUndef(a)||a(b,d))c=d;return c},b)},toArray:function(){return f(function(a,b){return b})},JSONStringify:function(){var b,d,c=!1;t.Prototype&&t.Prototype.Version&&
-1===t.Prototype.Version.indexOf("1.7")&&(c=!0);c&&(d=Array.prototype.toJSON,delete Array.prototype.toJSON);b=JSON.stringify(a);c&&(Array.prototype.toJSON=d);return b}}};e.toBase=function(a,c){var d,b=0>a,f="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".split(""),g=[];a=b?-a:a;do d=a%c,g.push(f[d]),a=(a-d)/c;while(0<a);g=g.reverse().join("");return b?"-"+g:g};e.isDef=function(a){return"undefined"!==typeof a};e.isUndef=function(a){return!e.isDef(a)};e.isBool=function(a){return"boolean"===
typeof a};e.noop=function(){};e.identity=function(a){return a};e.isFunction=function(a){return"function"===typeof a};e.isStr=function(a){return"string"===typeof a};e.useIfDef=function(a){return e.isDef(a)?a:!1};e.stringifyTriState=function(a){return!0===a?1:!1===a?0:"na"};e.resolve=function(a){var c=e(arguments).toArray();c.shift();return e.isFunction(a)?a.apply({},c):a};e.flatJSONParse=function(a){var c,d,b,f=/"(\w+)":(\d+|(?:"([^"]*)"))/g,g={};for(b=f.exec(a);b;)c=b[1],d=b[3],b=b[2],g[c]=d||+b,
b=f.exec(a);return g};var Ya=function(a,c,d,b,f,g,m){g=g||b.parentNode||b.parent;var k=function(){var d=w.embedded?a.calcDims():c.calcDims(b,g);if(f===h.DETECTION_METHODS.VIDEO&&w.embedded){var e=(new F(b)).getRounded();try{d.set("width",e.width),d.set("height",e.height)}catch(k){r.trigger("error",h.ERROR_CODES.VIDEO_IN_IFRAME_DIMS_CALC)}}else f===h.DETECTION_METHODS.AD_PLACEHOLDER&&d.treatAsPlaceholder();return d},q=function(){var b=!l.mobOrTab&&(w.friendly||e.isDef(t.mozInnerScreenX))&&m.on("offscreen"),
c=k(),g=new F(A.calcWinDims()),b=new F(b?A.calcMonDims():{}),q=f===h.DETECTION_METHODS.VIDEO&&w.embedded?a.getClippedDims():new F({});return d.calcPercentInView(c,g,b,q)},n=function(){return d.calcInitialViewState(q())},p=function(){return b===t?!1:k().isHidden()};(function(){var a=b===t?x.body:b;B.addEvent(a,"click",function(){r.trigger("adComponentClicked")});B.addEvent(a,"mouseover",function(){r.trigger("adComponentMousedOver")})})();return{getAdNode:function(){return b},isNode:function(a){return b===
a},isHidden:p,isObstructed:function(){return!1},getDims:k,getPercentInView:q,getLocationState:n,getOnPageViewability:function(){return p()?h.OUT_OF_VIEW:n()},getDetectionMethod:function(){return f},getContainerDims:function(){return F(g)},refresh:function(){var a,d=b.parentNode;if(d){for(;b!==t&&d&&d!==x&&!a;)a=d===g,d=d.parentNode;a||(g=b.parentNode)}}}},Za=function(a,c,d,b){var f=[],g=function(){return f[0]&&f[0].getDetectionMethod()===h.DETECTION_METHODS.AD_PLACEHOLDER},m=function(e,k,q){var m=
g()||0===f.length;e=Ya(a,c,d,e,k,q,b);m&&k!==h.DETECTION_METHODS.AD_PLACEHOLDER&&r.trigger("primaryadfound",e);g()&&f.shift();f.push(e)},k=function(){var a=0,b=0;e(f).each(function(d,c){var f;f=c.getDims();f.hasValidDims()&&(f=f.area(),a+=f,b+=c.getPercentInView()/100*f)});return{totalArea:a,totalInView:b}},q=function(){var a=k();return s.round(a.totalInView/a.totalArea*100)},n=function(){var a=k().totalArea>=h.MRC_LARGE_AD_SIZE;return d.calcInitialViewState(q(),!1,b.on("largeAd")&&a)},p=function(a){var b=
-1;e(f).each(function(d,c){c.isNode(a)&&(b=d)});return b},u=function(a){return function(){return f[0]&&f[0][a]()}};r.on("adComponentAdded",function(a){e(a).each(function(a,b){-1===p(b)&&m(b,h.DETECTION_METHODS.MUTATION)})});r.on("adComponentRemoved",function(a){e(a).each(function(a,b){var d=p(b);-1<d&&f.splice(d,1)})});return{getOriginatingNode:u("getAdNode"),getDims:u("getDims"),isObstructed:u("isObstructed"),getDetectionMethod:u("getDetectionMethod"),getContainerDims:u("getContainerDims"),getViewState:n,
getPercentInView:q,isHidden:u("isHidden"),isUsingPlaceholder:g,hasAd:function(){return!!f.length},refresh:function(){e(f).each(function(a,b){b.refresh()})},addAdComponent:m,getOutOfViewReasons:function(){var a=[],b=f[0],d=h.OUT_OF_VIEW_REASONS,c=n();c!==h.OUT_OF_VIEW&&c!==h.PARTIAL_VIEW_MINUS||a.push(d.GEOM);b.isHidden()&&a.push(d.HIDDEN);b.isObstructed()&&a.push(d.OBSTRUCTION);return a},getComponentCount:function(){return f.length}}},$a=function(a){var c=!1;if(!e.isUndef(t.MutationObserver)){var d=
new MutationObserver(function(a){s.execAtEndOfThread(function(){c&&e(a).each(function(a,b){b.addedNodes.length&&r.trigger("adComponentAdded",b.addedNodes);b.removedNodes.length&&r.trigger("adComponentRemoved",b.removedNodes)})})}),b=function(){c=!0;setTimeout(function(){c=!1},40)};r.on("adComponentClicked",b);r.on("adComponentMousedOver",b);try{d.observe(x.body,{attributes:!0,childList:!0,characterData:!0})}catch(f){a.add(h.ERROR_CODES.AC_WATCHER)}}},Ua=function(){var a,c,d=!1,b=r.request("mPage"),
f=function(){!d&&c&&a&&!b.isHidden()&&(d=!0,r.trigger("sendDt",h.DT_CODES.LARGE_BILLABLE))};r.on("primaryadfound",function(b){a=b.getDims().area()>=h.MRC_LARGE_AD_SIZE;f()});r.on("impressionsent",function(){c=!0;f()});b.onHiddenChange(f)},oa=function(){var a=[],c={},d={percentInView:"piv",sl:"vs",reason:"r",width:"w",height:"h"};r.on("newScreenEvent",function(b){b=e(b).selectProperties(e(d).keys());b=e(b).asStrings();var f=e(b).compareTo(c);f&&(f.t=w.getTagTime(),a.push(f));e(c).mixin(b)});return{toString:function(){return e(a).toION(d)}}},
ab=function(a,c,d,b,f,g,m){var k;(function(){var g=d.getRounded(),e=g.width-5,p=g.height-5,u=0.5*g.width+1,g=0.5*g.height+1;k=[new a(c,e,p,f,m,b),new a(c,e,5,f,m,b),new a(c,5,p,f,m,b),new a(c,5,5,f,m,b),new a(c,u,g,f,m,b)]})();return{getNumInView:function(){var a=[],b=0;e(k).each(function(b,d){var c=d.isInView()?1:0;a.push(c)});g.addItem({output:a.join(".")},"pvs");e(a).each(function(a,d){b+=d});return b},getPctInView:function(a){return 5===a?100:3<=a?51:0},isReady:function(){var a=!0;e(k).each(function(b,
d){d.isNotReadyToReport()&&(a=!1)});return a},remove:function(){e(k).each(function(a,b){try{b.remove()}catch(d){}})}}},bb=function(a,c,d,b,f,g,m,k){var q=new a(V,x.body,c,b,f,m,k),n,p,u=0;d=d||e.noop;n=setInterval(function(){q.isReady()&&!p?(p=!0,d(),clearInterval(n)):(5===++u||p)&&clearInterval(n)},50);return{checkViewable:function(){var a=q.isReady(),b=q.getNumInView(),b=q.getPctInView(b),c=g.calcInitialViewState(b,!0);a&&!p&&(p=!0,d());return{str:a?c:h.NA,pct:a?b:-1}},removePixels:function(){q.remove()}}},
da=function(a,c,d,b,f,g){var m,k,q=c.getRounded(),n=[],p=!1,u=0,C=b.on("largeAd")&&c.isMrcLarge()?cb(q):db(q),y=function(){var a;if(!p)for(p=!0,a=0;a<n.length;a++)if(n[a].isNotReadyToReport()){p=!1;break}return p},v=function(){var a=0;e(n).each(function(b,d){d.isInView()&&(a+=1)});return C.getPctInView(a)};(function(){var d=C.get();e(d).each(function(d,c){var e=new a(x.body,c.x,c.y,b,f,g);e.weight=c.weight;n.push(e)})})();d=d||e.noop;m=setInterval(function(){y()&&!k?(k=!0,d(),clearInterval(m)):(5===
++u||k)&&clearInterval(m)},50);return{checkViewable:function(){var a=y(),f;a&&(f=b.on("largeAd")&&c.isMrcLarge()?30:50,f=v()>=f?h.IN_VIEW:h.OUT_OF_VIEW);a&&!k&&(k=!0,d());return{str:a?f:h.NA,pct:a?v():-1}},removePixels:function(){e(n).each(function(a,b){try{b.remove()}catch(d){}})}}},S=function(){var a=new eb,c=new fb;return e(a).mixin(c)},fb=function(){var a={},c=function(d,b){a[d]=a[d]||new W;a[d].push(b)};return{on:function(a,b){b?c(a,b):e(a).each(c)},trigger:function(d){var b,c=e(arguments).toArray();
if(b=a[d])c.shift(),b.run.apply({},c)}}},V=function(a,c,d,b,f,g,m){var k=b.on("nextcocoaie")&&(g.browserIs(h.BROWSERS.IE)||g.browserIs(h.BROWSERS.MSEDGE)),q=!1,n,p,u,C,y,v=function(a,b){return'<param name="'+a+'" value="'+b+'"/>'},D=function(a,b){return a+'="'+b+'" '},E=function(){if(z()&&!q){n.style.height="1px"===n.style.height?"2px":"1px";try{n.confirmResize()}catch(a){q=!0,r.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}}},z=function(){var a=!1;try{a=n&&e.isFunction(n.jsHandshake)}catch(b){}return a},
G=function(){if(q)return!1;var a;try{if((a=y||z())&&!u){y=!0;var b=e.flatJSONParse(n.jsHandshake());u=b.id;if(e.isUndef(u))throw"corrupted Flash pixel message received";C=1===+b.isInView}}catch(d){a=!1,q=!0,r.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}return a};B.addEvent(t,"message",function(a){try{var b=e.flatJSONParse(a.data);"IASCOCOA"===b.type&&b.id===u&&(C=1===+b.isInView)}catch(d){r.trigger("error",h.ERROR_CODES.FLASH_API_ACCESS)}});var H=function(a,b,d){var c;c=new M;var f=l.cocaPuffsPath;
c.sub("static");c.master(c.master().split(":")[0]);f&&(c.master(f),c.sub(""));var f=c+(k?"/detector_4_2_IE.pix":"/detector_4_1.pix"),e=v("allowscriptaccess","always"),m=v("movie",f)+v("play","true")+v("loop","true");k&&(m+=v("wmode","transparent"));g.browserIs(h.BROWSERS.IE)?(c=x.createElement("div"),c.innerHTML="<object "+D("id","blag"+l.birthdate+s.random())+D("classid","clsid:D27CDB6E-AE6D-11cf-96B8-444553540000")+D(h.IAS_DETECTOR,"true")+D("type",h.FLASH_MIME)+D("data",f)+">"+m+e+"</object>",
n=c.firstChild):(n=x.createElement("object"),n.data=f,n.type=h.FLASH_MIME,n.innerHTML=e,n[h.IAS_DETECTOR]="true");n.style.position="absolute";n.style.width="1px";n.style.opacity="0";n.style.height="0px";c=n;f=c.style;f.left=b+"px";f.top=d+"px";a.appendChild(c);f.height="1px";k&&setInterval(E,100);return c}(a,c,d);return{isInView:function(){var a;if(G()){try{a=C}catch(b){y=!1,r.trigger("error",h.ERROR_CODES.COCOA_GONE)}g.browserIs("w")&&void 0!==a&&(n.style.height=p?"1px":"2px",p=!p)}return G()&&a},
isNotReadyToReport:function(){return!G()},createdFlash:n,remove:function(){H.parentNode&&H.parentNode.removeChild(H)}}},Y=function(){var a=function(d,b,c){var g=b.length,e=d.frames;c&&c(d,b);if(e.length){for(d=0;d<e.length;d++)b[g]=d,a(e[d],b,c);b.pop()}},c=function(d){a(top,[0],d)};return{traverse:c,getFrames:function(a){var b=[];c(function(a){b.push(a)});return e(b).filter(a)}}},W=function(){var a=[];return{push:function(c){a[a.length]=c},run:function(){var c=arguments;e(a).each(function(a,b){b.apply({},
c)})}}},ea=function(a){return{doEligibleJobs:function(c){var d=a[0],b=d&&d.time;b&&c>=b&&(d.task(),a.shift())},getNextJob:function(){return a[0]}}},gb=function(){var a=function(a,d,b,f){var g,m=e.noop,k;if(JSON&&JSON.parse)try{g=JSON.parse(a.data),k=a.source,d(g)&&(f&&(m=function(){(new Z(k)).send(function(){return f(k)})}),b(a,g,m))}catch(q){g&&r.trigger("error",h.ERROR_CODES.MESSAGE_LISTENER)}};return{listen:function(c,d,b){B.addEvent(t,"message",function(f){a(f,c,d,b)})}}},Z=function(a){var c=
function(a){return e(a).mapToObj(function(a,d){var c;e.isFunction(d)||(c={},c[a]=d);return c})};return{send:function(d){if(JSON&&JSON.stringify){var b=e(a).isObj()?[a]:(new Y).getFrames(a);e(b).each(function(a,b){var m;m=e.resolve(d,b)||{};m.sentTime=s.now();m=c(m);b.postMessage(e(m).JSONStringify(),"*")})}}}},ra=function(a){var c=0,d={},b=function(a,b,d){if(e.isUndef(a.output))throw Error("item with id "+b+' must have "output" method');this.item=a;this.id=b||++c;this.props=d||{};this.output=function(){return e.isFunction(a.output)?
a.output():a.output}},f=function(a,c,f){a=new b(a,c,f||{});d[a.id]=a};a.on("addOutputItem",function(a,b,d){f(a,b,d)});return{addItem:f,iterate:function(a){var b,c,f=[];for(b in d)d.hasOwnProperty(b)&&(c=a(b,d[b]))&&f.push(c);return f},getItem:function(a){return d[a]}}},cb=function(a){var c=a.width-5,d=a.height-5,b=0.5*a.width+1,f=0.5*a.height+1,g=0.3*a.width+1,e=0.7*a.width+1,k=0.3*a.height+1,q=0.7*a.height+2,n,p=function(b,d){1>b&&(b=1);1>d&&(d=1);b>a.width&&(b=0!==a.width?a.width:1);d>a.height&&
(d=0!==a.height?a.height:1);return{x:s.floor(b),y:s.floor(d)}};n=[p(c,d),p(c,5),p(5,d),p(5,5),p(b,f),p(g,k),p(e,k),p(g,q),p(e,q)];return{get:function(){return n},getPctInView:function(a){var b;0===a?b=0:1===a?b=10:2===a?b=20:5>a?b=30:7>a?b=50:9>a?b=70:9===a&&(b=100);return b}}},db=function(a,c){var d=0.5*a.width+1,b;b=[{y:s.floor(0.5*a.height+1),x:s.floor(d)}];return{get:function(){return b},getPctInView:function(a){return 1===a?50:0}}},eb=function(){var a={},c=function(d,b){a[d]=b};return{request:function(d){var b,
c=a[d],g=e(arguments).toArray();g.shift();e.isUndef(c)||(b=e.isFunction(c)?c.apply({},g):c);return b},provide:function(d,b){b?a[d]=b:e(d).each(c);return b}}},Fa=function(a,c,d){return{collect:function(){var b=a.find(),c=b.getOutOfViewReasons(),g=d.isHidden(),m=F(A.calcWinDims()),k=b.getDims();if(!m.hasValidDims()||!k.hasValidDims())return{viewState:h.NA,posViewState:h.NA,embedded:w.embedded,winDimensions:m,adDimensions:k};!0===g&&c.push(h.OUT_OF_VIEW_REASONS.FOCUS);return{winDimensions:m,adDimensions:k,
containerDimensions:b.getContainerDims(),method:b.getDetectionMethod(),viewState:c.length?h.OUT_OF_VIEW:b.getViewState(),percentInView:b.getPercentInView(),reason:c.join("."),obstructed:e.stringifyTriState(b.isObstructed()),isHidden:e.stringifyTriState(b.isHidden()),tabHidden:e.stringifyTriState(g),posViewState:b.getViewState(),adCompCount:b.getComponentCount()}}}},hb=function(a){a=a||e.identity;var c=[],d=s.now(),b=function(){var a=s.now();c.length&&(c[c.length-1].duration+=a-d,d=a)};return{clear:function(){b();
c=[]},fastForward:b,get:function(){return c},hasAlwaysBeen:function(a){return 1===c.length&&c[0].state===a},addState:function(d){var g=c[c.length-1];d=a(d);b();0!==c.length&&d===g.state||c.push({state:d,duration:0})}}},ib=function(a){var c=a||1,d=0,b=0,f=0,g=0;return{start:function(){0===d%c&&(f=s.now())},stop:function(){0===d%c&&(g+=s.now()-f,b++);d++},getTime:function(){return g},getCount:function(){return b}}},fa=function(a){var c=0,d=w.getTagTime(),b=0,f,g;return{getTotalTime:function(){return b},
stop:function(){c=0;d=w.getTagTime()},mark:function(){f=w.getTagTime()-d;c+=f;c>a&&(g=c-f<a,b+=g?c:f);d=w.getTagTime()}}},M=function(a){var c=/((http|https):\/\/(([^\/\.]*)\.([^\/]*)))(?:\/(.[^?]*))*/.exec(a||l.adsafeSrc||l.requrl),d=c[2],b=c[4],f=c[5],g=a?c[6]:"",m,k=function(a){e.isDef(a)&&(b=a);return b},q=function(a){e.isDef(a)&&(f=a);return f},n=function(){var a="";e(m).each(function(b,d){a+="&"+b+"=";a=e(d).isObj()?a+("{"+e(d).toParams()+"}"):a+d});return"?"+a.substr(1)};return{fullDom:c[1],
sub:k,master:q,setParam:function(a,b){m=m||{};m[a]=m[a]||{};e(b).isObj()?e(m[a]).mixin(b):m[a]=b},path:function(a){g=a},_getQsParams:function(){return m},toString:function(){var a=k()?k()+".":"",b=g?"/"+g:"",c=m?n():"";return d+"://"+a+q()+b+c}}},Wa=function(){var a=A.appendElement("iframe",{name:"hpif",style:"display:none"}),c=function(d){a.contentWindow[d.pieces.join("")]=function(){return{play:function(){r.trigger("addOutputItem",{output:d.abbr},"vh",{minDt:!0,type:h.DT_CODES.VH});r.trigger("sendMinDt",
h.DT_CODES.VH)}}}};e([{pieces:["jwp","la","yer"],abbr:"j"},{pieces:["flo","wpl","ayer"],abbr:"f"}]).each(function(a,b){c(b)})},Ea=function(a,c,d,b,f,g){var e=-1!==l.mode.indexOf("jsvid"),k=l.contextNode.parentNode,q=r.request("mobileApp"),n=Za(b,a,d,g);$a(c);return{find:function(){var a,b=h.DETECTION_METHODS,d=function(d){var c=A.findChildWithLargestContent(k);1<A.getNodeArea(c)&&!c[h.IAS_DETECTOR]?n.addAdComponent(c,d||b.AD_HUNT,k):n.hasAd()||(a=A.getPlaceholderSpan(),k.insertBefore(a,l.contextNode.nextSibling),
n.addAdComponent(a,d||b.AD_PLACEHOLDER))};if(n.isUsingPlaceholder()||!n.hasAd())q.isMobileAppEnvironment()?d(q.getDetectionMethod()):e?n.addAdComponent(f.findAdNode(),b.VIDEO):w.embedded?n.addAdComponent(t,b.IFRAME):d();return n},getDetectionMethod:function(){},isAdDetected:function(){return!0!==n.isUsingPlaceholder()},getOriginatingElement:function(){return n.getOriginatingNode()},getParent:function(){return k}}},Va=function(a){var c=function(a,b){var c;b&&b.id&&(c=b.id.replace(/[^\w-_]/g,""));return c};
(function(){var d;try{if("jload"===l.mode&&a.on("slid")&&w.friendly&&!w.isMobileApp()){var b,f;if(b=A.getOurNodeInTop()){var g=A.getAncestorNodes(b);f=e(g).map(c)}(d=f=f&&e(f).toION())&&r.trigger("addOutputItem",{output:d},"slid",{type:h.DT_CODES.ADTALK})}}catch(m){r.trigger("error",h.ERROR_CODES.AD_SLOT_ID)}})()},Ja=function(a,c,d,b,f){var g=function(a,b,d){f.addItem({output:a+"."+b+"."+d},"ctpl")},m=function(f){try{c.diagnostic("c");var q=f.length,m=0,p=0;g(q,0,0);e(f).each(function(d,c){a.send(c.replace("%%CBS%%",
b.getCacheBustId()),function(){g(q,m,++p)},!0);g(q,++m,p)})}catch(u){d.add(h.ERROR_CODES.AT_SEND)}};return{init:function(){try{var b=(new M).fullDom;"/"!==b.slice(-1)&&(b+="/");b+="tpl?asId="+l.asid;a.jsonp(b,m)}catch(c){d.add(h.ERROR_CODES.AT_INIT)}}}},Ia=function(a,c,d,b){return{enabled:"true"===l.useBapiCallback,callback:function(c){d.trigger("sendDiag");try{"true"===l.accountForSadImps&&b.measure(c),l._onAPIResult&&l._onAPIResult(c)}catch(g){a.add(h.ERROR_CODES.BAPI_CALLBACK),d.trigger("sendDiag",
"bapiClient")}}}},za=function(){var a=h.BROWSERS,c,d=function(){var a="0",b=s.getWindow(),d=function(a){return a.replace(/\D+/g,",").match(/^,?(.+),?$/)[1].split(",").join(".")};try{try{var c=s.getNewActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{c.AllowScriptAccess="always"}catch(f){a="6"}}catch(g){}a=d(s.getNewActiveXObject("ShockwaveFlash.ShockwaveFlash").GetVariable("$version"))}catch(e){try{b.navigator.mimeTypes[h.FLASH_MIME].enabledPlugin&&(a=d((b.navigator.plugins["Shockwave Flash 2.0"]||
b.navigator.plugins["Shockwave Flash"]).description))}catch(m){}}return a},b=function(){e.isUndef(c)&&(c=d());return c},f=function(a){return m()===a},g=function(){var a=s.getDoc();return a&&a.documentMode?a.documentMode:h.NA},m=function(){var b="u",d=s.getWindow();try{e.isDef(d.opera)&&e.isDef(d.opera.buildNumber)?b=a.OPERA:e.isDef(d.mozInnerScreenY)?b=a.GECKO:e.isDef(d.chrome)&&e.isDef(d.chrome.csi)?b=a.CHROME:e.isDef(d.msWriteProfilerMark)&&e.isDef(d.crypto)?b=a.MSEDGE:e.isDef(d.attachEvent)||e.isDef(d.msCrypto)?
b=a.IE:e.isDef(d.WebKitPoint)&&(b=a.WEBKIT)}catch(c){}return b};return{browserIs:f,hasFlashEnabled:function(){return"0"!==b()},getFlashVersion:b,getDocumentMode:g,getBrowserType:m,getUserAgent:function(){var a=!1,b=s.getWindow();e.isDef(b.navigator)&&e.isDef(b.navigator.userAgent)&&(a=b.navigator.userAgent);return a},params:function(){var d=m(),c=b(),n=5,p=s.getWindow(),u=s.getDoc();f(a.IE)?p.msCrypto?n=11:p.atob?n=10:p.addEventListener?n=9:p.JSON&&u.querySelector?n=8:p.XMLHttpRequest?n=7:u.compatMode&&
(n=6):n=h.NA;var p=g(),u=["{45EA75A0-A269-11D1-B5BF-0000F8051515}","{3AF36230-A269-11D1-B5BF-0000F8051515}","{89820200-ECBD-11CF-8B85-00AA005B4383}"],l=h.NA,y=s.getDoc(),v=y.createElement("div");if(f(a.IE))try{if("-ms-ime-align"in y.documentElement.style)l="11";else for(v.style.behavior="url(#default#clientcaps)",y=0;y<u.length&&!(l=v.getComponentVersion(u[y],"componentid").replace(/,/g,"."));y++);}catch(r){}u=l;l=h.NA;v=s.getWindow();e.isDef(v.navigator)&&e.isDef(v.navigator.appName)&&(l=v.navigator.appName.toLowerCase()[0]);
return{br:d,fv:c,bv:n,dm:p,abv:u,an:l}}}},Pa=function(a){var c=0.5<=s.random()?"cdn":"collo",d=function(){a.trigger("sendDiag",c+"Test","cdnTest")};return{init:function(){var b,f=l[c+"TestUrl"];f&&(b=-1===f.indexOf("?")?"?":"&",f=f+b+"asid="+l.asid,a.trigger("exec",f,d))}}},wa=function(a,c){var d=function(a,b){var d,c,f=l.contextNode.parentNode;b=b||a;a=1<arguments.length?a:"script";d={script:['<script type="text/javascript" src="','">\x3c/script>'],iframe:['<iframe width="100%" height="100%" frameborder="0" vspace="0" hspace="0" scrolling="no" marginheight="0" marginwidth="0" src="',
'"></iframe>'],img:['<img src="','"/>']}[a];c=d[0]+b+d[1];"true"===l.forceAppend?"script"!==a?(d=x.createElement("DIV"),d.innerHTML=c,f.appendChild(d.childNodes[0])):(d=x.createElement("SCRIPT"),d.src=b,f.appendChild(d)):x.write(c)},b=function(a,b,d){var c=!d&&B.getXHR2();c?(c.open("POST",a),c.onreadystatechange=function(){4===c.readyState&&200===c.status&&b&&b()},c.send()):(d=new Image,b&&(d.onload=b),d.src=a)},f=function(a,b){var d=x.createElement("script");d.type="text/javascript";d.src=a;b&&(d.onload=
b);e.isDef(l.contextNode.parentNode)&&l.contextNode.parentNode.appendChild(d)},g=function(d){e.isFunction(d)?d():"string"===typeof d?b(d,void 0,!0):a.add(h.ERROR_CODES.NOTIFY_CLIENT)},m=function(a,b,d,g){f(c.wrap(a,b,d,g))};r.on({addNode:d,send:b,exec:f,notify:g,jsonp:m});return{addNode:d,send:b,exec:f,notify:g,jsonp:m}},h={MAX_URL_LENGTH:2E3,MRC_LARGE_AD_SIZE:242500,FLASH_MIME:"application/x-shockwave-flash",IN_VIEW:"inView",OUT_OF_VIEW:"outOfView",PARTIAL_VIEW_PLUS:"partialViewPlus",PARTIAL_VIEW_MINUS:"partialViewMinus",
NA:"na",DT_CODES:{ADTALK:"a",DIAGNOSTIC:"b",THIRD_PARTY:"i",LARGE_BILLABLE:"l",VIDEO_EVENTS:"m",PING:"p",FULLY_INVIEW:"pf",QUARTILE_FULLY_INVIEW:"qf",SCA:"s",POS_INVIEW:"t",UNLOAD:"u",VIEWABILITY_READY:"v",VH:"vh"},DETECTION_METHODS:{AD_PLACEHOLDER:"s",AD_HUNT:"a",IFRAME:"i",VIDEO:"v",MRAID:"m",MUTATION:"c"},OUT_OF_VIEW_REASONS:{GEOM:"l",OBSTRUCTION:"o",FOCUS:"f",COLLAPSED:"c",HIDDEN:"h",VIDEO:"v"},ERROR_CODES:{GET_AD_DIMENSIONS:"a",AD_SLOT_ID:"A",BAPI_CALLBACK:"b",ADTALK_GENERAL:"c",COCOA_GONE:"C",
GET_SCREEN_LOC_GET_DIMENSIONS:"d",ADTALK_DUBIOUS:"D",VIDEO_IN_IFRAME_DIMS_CALC:"F",PHONE_HOME:"h",UID_GENERATION:"i",IMPRESSION_URLS:"I",JSINFO:"J",KILL_IT:"k",LOCATION_DETAILS:"l",IMPRESSION_LEADUP:"L",MESSAGE_LISTENER:"m",NOTIFY_CLIENT:"n",AT_INIT:"N",GET_SCREEN_LOC_PIV_CALC:"p",PLUGIN_PARSING:"P",GET_ELEM_STYLE:"s",AT_SEND:"S",NO_VIDEO_AD_NODE:"u",ENVIRONMENT:"v",GET_WIN_DIMENSIONS:"w",AC_WATCHER:"W",EXCHANGE_PARSING:"x",CHECK_SCREEN_LOC:"V",MOBILE_APP:"M",FLASH_API_ACCESS:"z"},IAS_DETECTOR:"iasdetector",
BROWSERS:{WEBKIT:"w",OPERA:"o",GECKO:"g",CHROME:"c",IE:"i",MSEDGE:"e"}},w=function(){var a=t!=top,c=function(){var a;try{a=!!top.document}catch(b){a=!1}return a}();return{embedded:a,friendly:c,friendlyIframe:a&&c,xDomainIframe:a&&!c,getTagTime:function(){return s.now()-l.birthdate},getPageTime:function(){return e.isDef(t.chrome)&&e.isDef(t.chrome.csi)&&e.isFunction(t.chrome.csi)?s.round(chrome.csi().pageT):h.NA},isVideo:function(){return-1!==l.mode.indexOf("jsvid")},isMobileApp:function(){return e.isDef(t.mraid)}}}(),
B={addEvent:function(a,c,d,b){e.isDef(a.addEventListener)?"mouseenter"===c?a.addEventListener("mouseover",B.mouseEnter(d),b):"mouseleave"===c?a.addEventListener("mouseout",B.mouseEnter(d),b):a.addEventListener(c,d,b):e.isDef(a.attachEvent)&&a.attachEvent("on"+c,d)},removeEvent:function(a,c,d){e.isDef(a.removeEventListener)?("mouseenter"===c?(c="mouseover",d=B.mouseEnter):"mouseleave"===c&&(c="mouseout",d=B.mouseEnter),a.removeEventListener(c,d)):e.isDef(a.detachEvent)&&a.detachEvent("on"+c,d)},mouseEnter:function(a){var c=
this;return function(d){var b=d.relatedTarget;this===b||c.isAChildOf(this,b)||a.call(this,d)}},isAChildOf:function(a,c){if(a===c)return!1;for(;c&&c!==a;)c=c.parentNode;return c===a},getStyle:function(a,c){var d="";x.defaultView&&x.defaultView.getComputedStyle?d=x.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(c=c.replace(/\-(\w)/g,function(a,d){return d.toUpperCase()}),d=a.currentStyle[c]);return d},getXHR2:function(a,c){var d,b;e.isDef(t.XMLHttpRequest)?(b=new XMLHttpRequest,
"withCredentials"in b&&(d=b)):e.isDef(XDomainRequest)&&(d=new XDomainRequest);return d}},Ha=function(a,c,d,b,f,g,m,k){var q=0,n=0,p=!1,u,C={},y=[h.DT_CODES.ADTALK],v=function(a,c,f,g,k){f=f||!d.on("postDts");var u=a===h.DT_CODES.VH||a===h.DT_CODES.DIAGNOSTIC||a===h.DT_CODES.ADTALK;if(b.impressionIsIdentifiable()&&(u||"n"!==m.getCurrentLoc()))try{var y=l.dtBaseURL,v=new M(y),D=s.now(),w=C[a];y||(v.path("dt"),d.on("usedtdomain")&&v.sub("dt"));t(v,a,c);k&&k.field&&v.setParam(k.field,k.value);g||z(v,
a);r.trigger("send",v,function(){n+=1;q=s.now()-D},f);a===h.DT_CODES.UNLOAD&&(p=!0);C[a]=e.isDef(w)?w+1:1}catch(x){__IntegralASDiagnosticCall("dt-"+a,x),r.trigger("error",h.ERROR_CODES.PHONE_HOME)}};a=function(a,b){var c={bapi:"a",bapiClient:"b",jload:"c",jss:"d",jsi:"e",cdnTest:"f",colloTest:"g"},f=l.mode,c=c[a]||c[f];d.on(b||f+"Diag")&&c&&v(h.DT_CODES.DIAGNOSTIC,-5,!0,!0,{field:"bkp",value:c})};var D=function(a){var b;a===h.DT_CODES.UNLOAD?b=-1:a===h.DT_CODES.ADTALK?b=-2:a===h.DT_CODES.VIEWABILITY_READY?
b=-3:a===h.DT_CODES.VIDEO_EVENTS?b=-4:a===h.DT_CODES.DIAGNOSTIC?b=-5:a===h.DT_CODES.THIRD_PARTY?b=-6:a===h.DT_CODES.QUARTILE_FULLY_INVIEW?b=-7:a===h.DT_CODES.LARGE_BILLABLE&&(b=-8);var d=C[a];e.isDef(d)&&-1!==y.indexOf(a)&&0!==d&&(b=b+"."+d);return b},t=function(a,d,c){c=e.isDef(c)?c:D(d);a.setParam("asId",l.asid);var g={c:b.getCacheBustId(),pingTime:c,time:w.getTagTime(),type:d};f.iterate(function(a,b){var c=b.props;!c.minDt||c.type&&c.type!==d||(g[a]=b.output())});a.setParam("tv",g)},z=function(a,
b){var e,p={};m.fastForward();b===h.DT_CODES.VIDEO_EVENTS&&(e=r.request("videoEventsString"))&&(p.ve=e,p.clog=k);b===h.DT_CODES.UNLOAD&&(p.ndt=n);-1!==l.mode.indexOf("jsvid")&&(p.vv=r.request("videoVersion"));p.NULL1=d.output();p.NULL2=m.stringify(10);p.em=w.embedded;p.fr=w.friendly;p.uf=u.useFlash()?1:0;p.e=c.toString();p.tt=l.mode;p.dtt=q;f.iterate(function(a,d){var c=d.props;c.minDt||c.type&&c.type!==b||(p[a]=d.output())});a.setParam("tv",p);a.setParam("br",g.getBrowserType())};r.on({sendDt:v,
sendMinDt:function(a,b){v(a,b,void 0,!0)},sendDiag:a});return{send:v,sendCookie:function(){var a;d.on("cookie")&&"true"===l.sendCookie&&l.protocol&&l.cookieDomain&&l.asid&&(a=l.protocol+"://"+l.cookieDomain+"?asid="+l.asid,r.trigger("send",a,e.noop,!0),n++)},unload:function(){p||v(h.DT_CODES.UNLOAD,-1,!0)},diagnostic:a,setViewabilityMod:function(a){u=a}}},F=function(a){var c={},d=!1,b=function(){var a={};e(c).each(function(b,d){a[b]=s.round(d)});return a},f=function(){return s.round(c.width)*s.round(c.height)};
(function(){var b;a!==t.parent&&(1!==a.nodeType?c=a:e.isDef(a.getBoundingClientRect)&&(b=A.getRect(a),e(c).mixin({x:e.useIfDef(b.x)||b.scrX,y:e.useIfDef(b.y)||b.scrY,scrX:b.scrX,scrY:b.scrY,width:b.width,height:b.height})))})();return{hasValidDims:function(){var a,b=e(c).find(function(b,d){a=!0;return isNaN(d)});return e.isDef(a)&&e.isUndef(b)},toString:function(){var a=b();return[a.scrX,a.scrY,a.width,a.height].join(".")},getRounded:b,set:function(a,b){c[a]=b},isHidden:function(){var b=1===a.nodeType?
A.nodeIsHidden(a):0===a.width||0===a.height;return d?!1:b},treatAsPlaceholder:function(){d=!0},area:f,isMrcLarge:function(){return f()>=h.MRC_LARGE_AD_SIZE}}},Aa=function(){return{calcDims:function(a,c){var d=new F(a),b=A.getClippedDimensions(a,c),f=d.getRounded();d.set("height",b.height<f.height?b.height:f.height||1);d.set("width",b.width<f.width?b.width:f.width||1);return d}}},A={nodeIsHidden:function(a){var c=this.getRect(a),d=0!==parseInt(B.getStyle(a,"width"))&&0===c.width,c=0===c.width||0===
c.height;a="hidden"===B.getStyle(a,"visibility");return d||c||a},calcWinDims:function(){var a,c,d;try{c=A.windowPosition(),d=A.windowSize(),a={scrX:s.round(c.scrX),scrY:s.round(c.scrY),width:s.round(d.width),height:s.round(d.height)}}catch(b){r.trigger("error",h.ERROR_CODES.GET_WIN_DIMENSIONS),a={}}return a},windowSize:function(){var a={},c,d;if(w.friendly)if(c=top.document,d=c.documentElement,c=c.getElementsByTagName("body")[0],e.isDef(top.innerWidth))a.width=top.innerWidth,a.height=top.innerHeight;
else if(e.isDef(d.clientWidth))a.width=d.clientWidth,a.height=d.clientHeight;else if(e.isDef(c.clientWidth))a.width=c.clientWidth,a.height=c.clientHeight;else throw a.width=a.height=0,"";else e.isDef(t.outerWidth)&&(a.width=t.outerWidth,a.height=t.outerHeight);return a},windowPosition:function(){var a=0,c=0;e.isDef(t.screenX)?(a=t.screenX,c=t.screenY):e.isDef(t.screenLeft)&&(a=t.screenLeft,c=t.screenTop);return{scrX:a,scrY:c}},getNodeArea:function(a){var c=-1;a&&(a=A.getRect(a),c=a.width*a.height);
return c},getRect:function(a){var c={},d=A.windowPosition();a=a.getBoundingClientRect();e.isUndef(a.x)&&(c.x=a.left,c.y=a.top);e.isUndef(a.width)&&(c.width=a.right-a.left,c.height=a.bottom-a.top);e(c).mixin(a,!0);c.scrX=d.scrX+c.x;c.scrY=d.scrY+c.y;return c},getIeDimObj:function(){return x.documentElement&&e.isDef(x.documentElement.clientWidth)&&x.documentElement||x.body},getPlaceholderSpan:function(){var a=x.createElement("span");e(a.style).mixin({width:"0px",height:"0px",display:"block",overflow:"hidden",
visibiility:"hidden"});a.innerHTML=".";return a},appendElement:function(a,c,d){var b=s.getDoc().createElement(a);c&&e(c).each(function(a,d){"style"===a&&"object"===typeof b.style&&"function"===typeof b.style.setAttribute?e(d.split(";")).each(function(a,d){var c=d.split(":");b.style[c[0].trim()]=c[1].trim()}):b.setAttribute(a,d)});d=d||l.contextNode.parentNode;d.appendChild(b);return b},getClippedDimensions:function(a,c){var d,b,f=1E4,e=1E4;d="absolute"===B.getStyle(a,"position");if(null!==a.parentNode&&
!d){do a=a.parentNode,d="OBJECT"!==a.tagName.toUpperCase(),b="inline"!==B.getStyle(a,"display"),d&&b&&(d=A.getRect(a),f=d.width<f?d.width:f,e=d.height<e?d.height:e);while(a.parentNode!==x&&a!==c)}return{width:s.round(f),height:s.round(e)}},findChildWithLargestContent:function(a){var c=function(b){for(;b.parentNode!==a&&"inline"!==B.getStyle(b.parentNode,"display");)b=b.parentNode;return b},d=null,b=function(b){var d,c,e=null,q=-1;if(b.length)for(d=0,c=b.length;d<c;d++){var n=b[d],p=A.getNodeArea(n),
u;if(u=p>q){u=void 0;if(u=n.parentNode===a)if(u=void 0,u="DIV"===n.nodeName)if(u=void 0,u=""===n.style.backgroundImage){var h=u=void 0,y=n.childNodes;for(u=0;u<y.length;u++)1===y[u].nodeType&&(h=!0);u=!h}u=!u}u&&(e=n,q=p)}return e}(function(a){var b,d,c,e,n=[],p="iframe img a object embed div".split(" ");b=0;for(d=p.length;b<d;b++){var u=a.getElementsByTagName(p[b]);if(u.length)for(c=0,e=u.length;c<e;c++)n.push(u[c])}return n}(a));b&&(d=c(b));return d},screenSize:function(){var a={width:-1,height:-1};
try{e.isDef(t.screen)&&(a={width:t.screen.width,height:t.screen.height})}catch(c){}return a},calcMonDims:function(){var a=e(A.screenSize()).mixin({scrX:0,scrY:0});e.isDef(screen.availLeft)&&(a={scrX:t.screen.availLeft,scrY:t.screen.availTop,width:t.screen.availWidth,height:t.screen.availHeight});return a},getOurIFrameInTop:function(){for(var a,c=s.getTop(),d=s.getWindow();d!=c;)a=d,d=a.parent;return a},getOurNodeInTop:function(){var a;w.friendly&&(a=w.embedded?(a=A.getOurIFrameInTop())&&a.frameElement:
l.contextNode);return a},getAncestorNodes:function(a){var c=[],d=a.ownerDocument&&a.ownerDocument.documentElement;if(d)for(;a.parentNode!==d;)c.push(a),a=a.parentNode;return c},getTagsNamed:function(a){return s.getDoc().getElementsByTagName(a)},containsScriptTagWithSrc:function(a){return!!e(A.getTagsNamed("script")).findFirst(function(c,d){var b=d.src;return e.isFunction(a)?a(b):b===a})}},xa=function(a){return{getProps:function(){var c={};try{var d=x.createElement("span");e(d.style).mixin({position:"absolute",
top:"150"});c={rpx:""===d.style.top?1:0}}catch(b){a.add(h.ERROR_CODES.ENVIRONMENT)}return c}}},qa=function(){var a={},c=function(d){e.isDef(a[d])?a[d]++:a[d]=1};r.on("error",function(a){c(a)});return{list:a,add:c,toString:function(){var d="",b;for(b in a)a.hasOwnProperty(b)&&(d+=b);return d},hasErrors:function(){for(var d in a)return!0;return!1}}},Sa=function(a,c){var d=function(a){var d=[];if(a&&a instanceof Array)d=e(a).map(function(a,b){return b.val}),d.push(l.adsafeSrc,l.requrl,l.reqquery);else throw Error("Unexpected data type in ExchangeParser.getUrlList");
return d};return{parse:function(b){try{var f,g=d(b),m=g&&g.length&&g.join("|"),k=l.exchList;m&&(f=e(k).map(function(a,b){return 0<=m.indexOf(O.rot(b))?a:void 0}),f.length&&c.addItem({output:f.join(".")},"ex",{type:"UFO"}))}catch(q){a.add(h.ERROR_CODES.EXCHANGE_PARSING)}}}},ma=function(){var a={},c=function(b,d){var c=RegExp(b+"(?=$|,)|"+b+":(?!,|$)(.?\\d*(?=,|$))").exec(l.jsFeatures);if(e.isUndef(a[b])||d)a[b]=!!(c&&!c[1]||c&&c[1]>100*s.random());return a[b]},d={fc:"forcecocoa",rt:"rattie",cb:"cachebust",
np:"nextcocoa",th:"tabHiddenDtCall",es:"everySecond"},b={gm:"use100v",fif:"useFIF"},f=function(){var c,f;c=e(d).mapToObj(function(b,d){var c={};c[b]=a[d]?1:0;return c});f=e(b).mapToObj(function(a,b){var d={};d[a]=g(b)?1:0;return d});return e(c).mixin(f)},g=function(a){a=l[a];return!0===a||"true"===a||e.isFunction(a)};e(d).each(function(a,b){c(b)});return{on:c,bootstrapOn:g,output:function(){return e(f()).toParams()}}},Ca=function(a){var c=h.BROWSERS,d=a.browserIs(c.GECKO)||a.browserIs(c.IE)||w.friendlyIframe||
!w.embedded;return{calcInitialViewState:function(a,c,e){var m={IN_VIEW:65,OUT_OF_VIEW:25,PARTIAL_VIEW:30},k={IN_VIEW:75,OUT_OF_VIEW:25,PARTIAL_VIEW:50},q=h.NA;e=e?m:k;if(d||c)q=a>=e.IN_VIEW?h.IN_VIEW:a<=e.OUT_OF_VIEW?h.OUT_OF_VIEW:a>=e.PARTIAL_VIEW?h.PARTIAL_VIEW_PLUS:h.PARTIAL_VIEW_MINUS;return q},calcPercentInView:function(a,d,c,m){var k=0,q=a;a.hasValidDims()&&!a.isHidden()&&(e([d,c,m]).each(function(a,b){if(b.hasValidDims()){var d=q.getRounded(),c=b.getRounded(),f=Math.max(d.scrX,c.scrX),e=Math.max(d.scrY,
c.scrY),g=Math.min(d.scrX+d.width,c.scrX+c.width),d=Math.min(d.scrY+d.height,c.scrY+c.height),g=g-f,d=d-e;q=F({scrX:f,scrY:e,width:0<g?g:0,height:0<d?d:0})}}),k=s.round(q.area()/a.area()*100));return k}}},ya=function(a){var c=!1;return{getCacheBustId:function(){var a=new Date,b=Date.parse("Jan 1 "+a.getFullYear()),a=a.getTime()-b;return e.toBase(a,62)},impressionIsIdentifiable:function(a){a&&(c=!0);return c},unq:function(){var d="";try{for(var b,c=t.Uint32Array&&t.crypto&&t.crypto.getRandomValues;30>
d.length;)c?(b=new Uint32Array(1),t.crypto.getRandomValues(b),d+=b[0].toString(16)):d+=(16*s.random()|0).toString(16);d=d.slice(0,30)}catch(e){a.add(h.ERROR_CODES.UID_GENERATION)}return d}()}},Ba=function(a){var c,d=function(){var b,d,c,g,p,u,l=s.getMaxNumber();b=s.getMaxNumber();c=s.getWindow();w.friendly?(b=f(),c=b.left,g=b.top,l=b.width,b=b.height,d=A.windowPosition(),p=d.scrX+c,u=d.scrY+g):a.browserIs(h.BROWSERS.IE)&&11!==a.getDocumentMode()?(u=p=0,c=function(a){p=a.screenX-a.clientX;u=a.screenY-
a.clientY},x.documentElement.attachEvent("onmousemove",c),x.documentElement.fireEvent("onmousemove"),x.documentElement.detachEvent("onmousemove",c)):e.isDef(c.mozInnerScreenX)&&(p=s.round(c.mozInnerScreenX),u=s.round(c.mozInnerScreenY));return{scrX:p,scrY:u,iFrameClippingWidth:l,iFrameClippingHeight:b}},b=function(){var a,b,d=c||A.getIeDimObj(),f=s.getWindow();e.isDef(f.innerWidth)?(a=f.innerWidth,b=f.innerHeight):d&&e.isDef(d.clientWidth)?(a=d.clientWidth,b=d.clientHeight,0===a&&0<d.offsetWidth&&
(a=d.offsetWidth),0===b&&0<d.offsetHeight&&(b=d.offsetHeight)):f.frameElement&&e.isDef(f.frameElement.clientWidth)&&(a=f.frameElement.clientWidth,b=f.frameElement.clientHeight);return{width:a,height:b}},f=function(a,b){a=a||s.getWindow();b=b||{top:0,left:0,width:s.getMaxNumber(),height:s.getMaxNumber()};for(var d,c=a.parent.document.getElementsByTagName("iframe"),e=!1,g=0,l=c.length;g<l;g++)if(d=c[g],d.contentWindow==a){e=!0;break}if(e){d=A.getRect(d);b.left+=d.left;b.top+=d.top;try{b.width=s.min(b.width,
d.width),b.height=s.min(b.height,d.height)}catch(y){r.trigger("error",h.ERROR_CODES.GET_AD_DIMENSIONS)}a!==s.getTop()&&f(a.parent,b)}return b},g=function(){var a={};try{a=e(d()).mixin(b())}catch(c){r.trigger("error",h.ERROR_CODES.GET_AD_DIMENSIONS)}return a};return{calcDims:function(){return new F(g())},waitForBody:function(a){var b=setInterval(function(){x.body&&(c=A.getIeDimObj(),clearInterval(b),a())},50)},getClippedDims:function(){var a=g();return new F({scrX:a.scrX,scrY:a.scrY,width:a.iFrameClippingWidth,
height:a.iFrameClippingHeight})}}},Na=function(a,c,d,b,f,g,m,k){var q=function(a,b){if(b>=h.MAX_URL_LENGTH)return"";var d,c,f=[],g=function(a){return-1!==a.key.indexOf("q")||-1!==a.key.indexOf("g")};d=e(a).map(function(a,b){if(g(b))return b});c=e(a).map(function(a,b){if(!g(b))return b});e(d.concat(c)).each(function(a,d){var c="adsafe_url="+d.val+"&adsafe_type="+d.key,e=f.join("&").length;c.length+e+b<=h.MAX_URL_LENGTH&&f.push(c)});return f.join("&")},n=function(a){var f=0,n=O.hashCode(l.asid),q="adsafe_jsinfo=",
v=k.needsFlash()?{viewState:h.NA}:k.checkScreenLoc(!0),r="c:"+b.getCacheBustId()+",sl:"+v.viewState+",em:"+w.embedded+",fr:"+w.friendly,t=d.on("postDts")&&B.getXHR2()?"p":"i",z=["pt:"+k.stringifyPingTimes()+(v.viewState!=h.NA?v.details:""),e(m.params()).toParams(),"id:"+l.asid];g.iterate(function(a,b){z.push(a+":"+b.output())});c.toString()&&z.push("e:"+c.toString());z.push(d.output());z.push("uf:"+(k.useFlash()?1:0));z.push("tt:"+l.mode);z.push("et:"+(s.now()-l.birthdate));z.push("uid:"+b.unq);z.push("v:1.31.0");
z.push("sp:"+("true"===l.jsDoSplit?1:0));z.push("ct:"+w.getPageTime());z.push("dtm:"+t);z.push("mn:"+l.mn);z.push("gtpl:"+("true"===l.getTpl?1:0));d.on("resolution")&&(z.push("wr:"+e(A.windowSize()).toArray().join(".")),z.push("sr:"+e(A.screenSize()).toArray().join(".")));-1===(""+n).indexOf(m.params().br.toUpperCase().charCodeAt(0))&&z.push("mf:"+n);var x=function(b){return q.length+a+b.length+5<=h.MAX_URL_LENGTH},H=function(a){if(a)return","+a};x(r)&&(q+=H(r),e(z).each(function(a,d){-1!==d.indexOf("id:")&&
x(d)?(q+=H(d),b.impressionIsIdentifiable(!0)):x(d)?q+=H(d):f+=1}),H("sp:"+("true"===l.jsDoSplit?1:0)));return q+=",ov:"+f};return{send:function(a){var b=f.baseUrl;try{b+=q(a,b.length)}catch(d){c.add(h.ERROR_CODES.IMPRESSION_URLS)}b+="&"===b.slice(-1)?"":"&";try{b+=n(b.length)}catch(e){c.add(h.ERROR_CODES.JSINFO),b+="adsafe_jsinfo=e:"+c.toString()}f.macroUrl&&(b+="&"===b.slice(-1)?"":"&",b+=f.macroUrl);try{f.sendImpression(b),r.trigger("impressionsent")}catch(g){__IntegralASDiagnosticCall("impsend",
g,l)}}}},Ka=function(a,c){return{init:function(d){a.jsonp(d,function(a){c.send(h.DT_CODES.THIRD_PARTY,void 0,!1,!0,{field:"tpiLookup",value:a})},!1,"callback")}}},Ga=function(a){var c=function(a,d){return{time:a,task:d}},d=function(a,d){d=d||e.noop;return function(g){return e(g).map(function(e,g){var q=g/1E3;return new c(g,function(){var c;c="";var e=w.isVideo()?2:1;q!==e&&(c+=q);c=l["_onInViewMRC"+c];r.trigger("sendDt",a,q);d(c)})})}};return{getJob:function(a,d){return new c(a,d)},getPingJobs:d(h.DT_CODES.PING,
function(b){"true"===l.useViewabilityNotification&&!a.skipAsFraudulent()&&b&&r.trigger("notify",b)}),getFullyInViewPingJobs:d(h.DT_CODES.FULLY_INVIEW),getPosInViewPingJobs:d(h.DT_CODES.POS_INVIEW)}},va=function(){var a=function(a,b){-1!==a.indexOf(b+"&")&&(b+="&");return a.replace(b,"")},c=function(a,b,c){var e=a.indexOf("?");b=b+"="+c;if(-1===e)return a+"?"+b;e++;return a.slice(0,e)+b+"&"+a.slice(e)};return{wrap:function(d,b,f,e){var m="__IntegralAS_"+l.asid.replace(/\-/g,"")+"_"+s.round(1E4*Math.random()),
k,q,n;e=e||"ias_callback";RegExp(e).test(d)&&(k=RegExp("("+e+"=)(.[^&]*)").exec(d)[0],q=k.split("=")[1],n=O.stringToFn(q),d=a(d,k));t[m]=function(a){b(a);f&&n&&n(a);t[m]=void 0};return d=c(d,e,m)}}},La=function(a,c){var d={jss:{isFW:!0,nodeType:"script"},jsi:{isFW:!0,nodeType:"iframe"},jload:{impressionMethod:function(a){r.trigger("send",a,function(){r.trigger("sendDiag")},!c.on("postMon"))}},bapi:{impressionMethod:function(b){r.trigger("jsonp",b,a.enabled?a.callback:e.noop,a.enabled?!0:!1)}},jsapi:{isFW:!0,
impressionMethod:function(b){r.trigger("jsonp",b,a.enabled?a.callback:e.noop,a.enabled?!0:!1)}},jsvid:{impressionMethod:function(a){r.on("adImpression",function(){r.trigger("send",a,e.noop,!c.on("postMon"))})}},fwjsvid:{isFW:!0,impressionMethod:function(a){var d="false"===l.fwMonitoring,c=function(a){a=a.split("/");a[3]="db2";a[4]="video";return a.join("/")};d&&r.trigger("jsonp",c(a),function(a){r.trigger("videoBlockResult",a)});r.on("adImpression",function(c){var g;if(g=d)g=c&&e.isBool(c.integral_didBlock)&&
0<=c.integral_timeToDecision;g&&(a=a.replace(/(adsafe_jsinfo=)([^&]*)/,"$1$2,abc:"+(c.integral_didBlock?1:0)+",abct:"+c.integral_timeToDecision));r.trigger("send",a,e.noop,!0)})}},jspix:{nodeType:"img"}};return new function(){var a=function(a){var b=-1===a.indexOf("?")?"?":"&";return a+b},c=d[l.mode],e=!!c.isFW,m=function(a){var b;b=r.request("mobileApp").isMobileAppEnvironment()&&l.mobFwUrl?l.mobFwUrl:a?l.adsafeSrc:l.requrl;a||(b+="?"+l.reqquery);return b}(e),k=m.indexOf("BEGIN__ADSAFE"),q=-1!==
k,n=q?m.slice(k):"",a=q?m.slice(0,k):a(m);return{isFW:e,baseUrl:a,macroUrl:n,sendImpression:function(a){c.nodeType?r.trigger("addNode",c.nodeType,a):c.impressionMethod(a)}}}},Ra=function(a,c){var d,b=l.mtCell,f=l.mtSample,g=0,m=0,k=[],q=null,n=null,p,u=function(a){try{var d=s.now()-q;g+=d;B.removeEvent("mousemove",y);k.push("{ht:"+g+",mm:{"+e(p).toParams()+"}}");c.addItem({output:"{cs:"+b+",sr:"+f+",ec:"+k.length+",me:["+k.slice(-10).join(",")+"]}"},"mt",{type:h.DT_CODES.UNLOAD})}catch(n){}},r=function(a){try{g=
0,p={},q=s.now(),B.addEvent(d,"mousemove",y)}catch(b){}},y=function(c){var g,q,k,h,u,l,y;try{null===n&&(n=d&&e.isDef(c.clientX)&&e.isDef(c.clientY));if(n&&0===m%f&&(u=a.calcDims(),-1!==u)){y=s.ceil(u.width/b);var r=c.clientX,t=c.clientY;k=w.embedded?r:r-u.x;h=w.embedded?t:t-u.y;g=s.floor(k/b);q=s.floor(h/b);l=g+q*y;p[l]?p[l]++:p[l]=1}m++}catch(C){}};return{init:function(){var b=setInterval(function(){try{a.isAdDetected()&&(d=a.getOriginatingElement(),B.addEvent(d,"mouseenter",r),B.addEvent(d,"mouseleave",
u),clearInterval(b))}catch(c){}},250)}}},s={execAtEndOfThread:function(a){setTimeout(a,0)},now:function(){return(new Date).getTime()},random:function(){return Math.random()},round:function(a){return Math.round(a)},ceil:function(a){return Math.ceil(a)},floor:function(a){return Math.floor(a)},min:function(){return Math.min.apply(null,arguments)},getWindow:function(){return t},getMaxNumber:function(){return Number.MAX_VALUE},getTop:function(){return top},getNewActiveXObject:function(a){return new ActiveXObject(a)},
getDoc:function(){return x}},sa=function(){var a,c=!1,d=new W,b=function(){var b=s.getWindow();return w.friendly&&b.top.document&&(e.isFunction(b.top.document.hasFocus)||e(b.top.document.hasFocus).isObj())&&!b.top.document.hasFocus()||(e.isDef(a.prop)?s.getDoc()[a.prop]:null)},f=function(){var c=s.getWindow(),e=function(){d.run(b())};B.addEvent(c,"focus",e,!0);B.addEvent(c,"blur",e,!0);a.event&&B.addEvent(s.getDoc(),a.event,e,!0)};a=function(){var a,b="hidden",d="visibilitychange",c=s.getDoc();e.isUndef(c.hidden)?
e(["moz","ms","webkit"]).each(function(f,p){var h=p+"Hidden";e.isDef(c[h])&&(b=h,d=p+d,a=!0)}):a=!0;return a?{prop:b,event:d}:{}}();return{isHidden:b,onHiddenChange:function(a){d.push(a);c||(c=!0,f())}}},ta=function(){var a=function(a){for(var b in a)if(a.hasOwnProperty(b)){var c=a[b];(""===c||"null"===c||"undefined"===c||null===c||e.isUndef(c))&&delete a[b]}return a},c=function(a){var b={},c,g;for(g in a)a.hasOwnProperty(g)&&(c=a[g],e.isUndef(b[c])?b[c]=g:b[c]+=g);a={};for(g in b)b.hasOwnProperty(g)&&
(c=b[g],a[c]=g);return a};return{detectTopURL:function(){var d=function(){var a={g:"",q:""};try{a.q=t.parent.parent.parent.parent.parent.parent.parent.parent.parent.parent.location.href}catch(b){var c=b.message,c=c.substring(c.lastIndexOf("<")+1,c.lastIndexOf(">")),d;if(d=e.isDef(c))if(d=!1,e.isDef(t.navigator)&&e.isDef(t.navigator.userAgent)){var f=t.navigator.userAgent.match(/Firefox\/([\.0-9]+)/);null!==f&&2==f.length&&(f=f[1].split("."),3==parseInt(f[0],10)&&6>=parseInt(f[1],10)&&(3==f.length?
13>=parseInt(f[2],10)&&(d=!0):d=!0))}d&&(a.g=c)}return a},b={};try{b.a=encodeURIComponent(top.location.href)}catch(f){}try{b.b=encodeURIComponent(parent.location.href)}catch(g){}if(w.embedded){try{b.c=encodeURIComponent(parent.document.referrer)}catch(m){}try{b.e=encodeURIComponent(t.document.referrer)}catch(k){}}try{"jsi"!==l.mode&&(b.d=encodeURIComponent(t.location.href))}catch(q){}try{b.f=encodeURIComponent(l.jsref)}catch(n){}try{var p=d();b.g=encodeURIComponent(p.g);b.q=encodeURIComponent(p.q)}catch(h){}var b=
a(b),b=c(b),d=[],r;for(r in b)b.hasOwnProperty(r)&&d.push({key:r,val:b[r]});d.sort(function(a,b){return a.val.length>b.val.length?1:a.val.length<b.val.length?-1:0});return d}}},Ta=function(a){return{hash:function(){for(var c=0,d=a.length,b=[],f;c<d;c++)f=a[c].filename.replace(/\.plugin$/,""),f=O.hashCode(f),f=e.toBase(f,62).slice(-4),b.push(f);return b},decode:function(c){var d,b;d=s.floor(s.random()*c.length);b=encodeURIComponent(a[d].filename.replace(/\.plugin$/,""));return[c[d],b]}}},pa=function(a){var c=
!1;return{measure:function(d){(c=0===d.rsa)&&l._onSuspicious&&a.trigger("notify",l._onSuspicious)},skipAsFraudulent:function(){return c}}},ua=function(){var a=[],c={},d={sl:"n",gsl:"gn",fsl:"fn"},b=0,f,g,m={i:0,o:0,n:0,pp:0,pm:0,gpp:0,gpm:0,gi:0,go:0,gn:0,fi:0,fo:0,fn:0},k=function(a){var b={},c=a.winDimensions,d=a.adDimensions;e.isDef(c)&&c.hasValidDims()&&(b.wc=c);e.isDef(d)&&d.hasValidDims()&&(b.ac=d,b.am=a.method,b.cc=a.containerDimensions);e({piv:"percentInView",obst:"obstructed",th:"tabHidden",
reas:"reason",cmps:"adCompCount"}).each(function(c,d){var f=a[d];e.isDef(f)&&(b[c]=f)});c=e(b).toParams();return""===c?"":","+c},q=function(a,b){var d=new hb(b);return c[a]=d},n=function(a,b){return(b||"")+{inView:"i",outOfView:"o",na:"n",partialViewMinus:"pm",partialViewPlus:"pp"}[a]},p=function(){e(d).each(function(c,d){m[d]+=a.length?g-b:g});b=g},l=function(b){a.length&&p();e(b).each(function(a,b){var c=d[a];c!==b&&"n"===c&&(m[b]+=m.n);d[a]=b});a.length||p()},s=function(a){var b,d=a.adDimensions.getRounded();
b=k(a);var f={sl:n(a.viewState),fsl:n(a.fState||h.NA,"f"),gsl:n(a.gState||h.NA,"g")};g=w.getTagTime();l(f);f.t=g;b=e({toString:function(){e(c).each(function(a,b){b.fastForward()});return"{"+e(f).toParams()+this.details+this.breakdowns+"}"},details:b,breakdowns:{piv:[],as:[],toString:function(){var a,b=function(a,b){return b.duration+"~"+b.state};a=""+("piv:["+e(this.piv).stringify(b)+"]");a+=",as:["+e(this.as).stringify(b)+"]";return",bkn:{"+a+"}"}},isInView:function(){return-1!==(h.IN_VIEW+"|"+h.PARTIAL_VIEW_PLUS).indexOf(a.viewState)},
isFullyInView:function(){var b=a.useCocoa?a.fullPercentInView:a.percentInView;return this.isInView()&&100===b}}).mixin(f);e(b).mixin(a);b.width=d.width;b.height=d.height;return b};(function(){q("piv",function(a){var b,c=a.percentInView,d=[1,25,30,50,75];100===c||0===c?b=c:(e(d).each(function(a,f){e.isUndef(b)&&c<f&&(b=d[a-1])}),e.isUndef(b)&&(b=d[d.length-1]));return b});q("as",function(a){a=a.adDimensions.getRounded();return a.width+"."+a.height})})();return{fastForward:function(){g=w.getTagTime();
p()},registerLocation:function(b){var g,q=!1;d.sl==n(b.viewState)&&a.length?(g=new s(b),a[a.length-1].details=g.details):(g=new s(b),a.push(g),f=b.viewState,q=!0);r.trigger("newScreenEvent",g);e(c).each(function(b,c){-1!=="piv|as".indexOf(b)?(q&&c.clear(),c.addState(g),a[a.length-1].breakdowns[b]=c.get()):c.addState(g)});return g},stringify:function(b){var c="";a.length&&(c=e({slTimes:"{"+e(m).toParams()+"}",slEvents:"["+a.slice(-b).join(",")+"]",slEventCount:a.length}).toParams());return c},createViewabilityTracker:q,
getCurrentLoc:function(){return n(f)}}},Oa=function(a){var c=l.asid,d=[0,1,4],b,f=function(){var a=setInterval(function(){t.postMessage({asid:c,ksca:"acsk",sender:"main"},"*")},50);t.addEventListener("message",function(b){b=b.data;"acsk"===b.ksca&&b.asid===c&&"main"!==b.sender&&("ack"===b.type&&clearInterval(a),"complete"===b.type&&(b.timeReturned=s.now(),g(b)),d.length&&(b=d.shift(),t.postMessage(m(b),"*")))})},g=function(b){var c=-5-0.1*b.targets,d=h.DT_CODES.SCA;b="{"+e(b).stringify(function(a,
b){var c;0===a.indexOf("time")?c=a+":"+b:"resultList"===a&&(c="rl:"+e(b).map(function(a,b){return"{"+e(b).toParams()+"}"}).join("."));return c})+"}";a.trigger("addOutputItem",{output:b},"sc",{type:d});a.trigger("sendDt",d,c)},m=function(){var a=0,d=c.replace("-",""),e=d.substr(-6);return function(f){for(var g=b,m=s.now(),h=f,l=[];h--;)l.push(d.substr(++a,3));return{scaUrl:g,targets:f,timeBegun:m,src:e,targetList:l,asid:c,ksca:"acsk",sender:"main",cap:1E6}}}();return{load:function(){if(!e.isUndef(t.Worker)&&
!e.isUndef(t.Blob)){var c=new M;c.sub("static");c.master(c.master().split(":")[0]);c.path("sca.js");b=c.toString();a.trigger("exec",b);f()}}}},O={rot:function(a){return a.replace(/[a-zA-Z]/g,function(a){return String.fromCharCode(("Z">=a?90:122)>=(a=a.charCodeAt(0)+13)?a:a-26)})},hashCode:function(a){var c=0,d,b,e;if(0===a.length)return c;d=0;for(e=a.length;d<e;d++)b=a.charCodeAt(d),c=(c<<5)-c+b,c|=0;return c},stringToFn:function(a){var c,d=t,b=a.split(".");for(a=0;a<b.length;a++)if(c=d,d=d[b[a]],
e.isUndef(d)||a===b.length-1&&!e.isFunction(d))return!1;return function(){d.apply(c,arguments)}}},na=function(a){var c,d,b,f=new S,g=new Y,m=new jb(f),h=new kb(f),q=new lb(f,a),n=e.isDef(t.JSON)&&e.isDef(t.postMessage),p=function(){e.isUndef(b)&&(b=new mb(f));return b},u=function(){f.provide({frameCollection:function(){return m},adProxy:function(){return h},adTalkMessage:function(a){return new nb(a)},idMapModule:p})};return{isApplicable:function(){return n},start:function(){u();h.createNew(l);g.traverse(m.addFrame);
q.startListening();q.sendToKnownFrames()},sendAdTalkCall:q.sendAdTalkCall,getFrameMap:function(){e.isUndef(c)&&(c=new ja(f));return c},getFrameMapIncludingPeerCase:function(){e.isUndef(d)&&(d=new ja(f,!0));return d},getIdMap:p}},nb=function(a){var c={messageContent:a||{},srcAsid:l.asid,srcIsEmbedded:w.embedded,srcBirthdate:l.birthdate,iasCommonId:l.asid.split("-")[2],updateMessage:function(d){c.messageContent=d(a)}};return c},ob=function(a,c,d,b){var f,g=a==t;f={position:c.slice(0),id:c.join("-"),
isMe:g,isLeaf:!a.frames.length,adProxies:g?d:[],selfDescription:void 0,unifiedId:l.birthdate,srcIsEmbedded:b?b.srcIsEmbedded:void 0,inbox:b?[b]:[],getDomObj:function(){return a},getStringifiedPosition:function(){return e(f.position).map(function(a,b){return e.toBase(Number(b)+1,36)}).join("")},isValidForMapping:function(){return f.isLeaf||f.isMe||e.isDef(f.selfDescription)},markTagAsReported:function(){f.adProxies.length&&e(f.adProxies).each(function(a,b){b.isReported=!0})},hasUnreportedTag:function(){var a=
e(f.adProxies).findFirst(function(a,b){return!b.isReported});return e.isDef(a)}};var m=function(a){var b=f.adProxies;a=a.adProxies;var c=[];b.length&&a.length?e(a).each(function(a,d){h(b,d)&&c.push(d)}):c=a;f.adProxies=b.concat(c)},h=function(a,b){return!e(a).find(function(a,c){return c.adSafeId&&c.adSafeId===b.adSafeId})},q=function(a){e(f.inbox).find(function(b,c){return c.srcAsid&&c.srcAsid===a.srcAsid})||f.inbox.push(a)};f.addInformationFromSrc=function(a,b){m(b);q(a);f.srcIsEmbedded=a.srcIsEmbedded;
f.selfDescription=b};return f},jb=function(a){var c=[],d={},b={noMe:!0};return{addFrame:function(e,g,m){var h=a.request("adProxy").getAll();e=new ob(e,g,h,m);c.push(e);d[e.id]=e;e.isMe&&(b=e);return e},getFrame:function(a){return d[a]},list:c,dictionary:d,getMe:function(){return b},markAllTagsAsReported:function(){e(c).each(function(a,b){b.markTagAsReported()})}}},ja=function(a,c){var d=function(a,d){var e=d.adProxies,h="";if(d.isValidForMapping()){if(c)h+=b(e,d.getStringifiedPosition());else{var q;
q=""+d.getStringifiedPosition();q+=d.isMe?"*":"";q+=e.length?"."+e[0].tagId:"";h+=q}return h}},b=function(a,b){var c="";return c=a.length?c+e(a).stringify(function(a,c){return b+(l.asid===c.adSafeId?"*":"")+"."+c.tagId},"|"):c+b};return{output:function(){var b=a.request("frameCollection"),c=e(b.list).stringify(d,"|");return e.toBase(b.getMe().unifiedId,62)+"+"+c}}},mb=function(a){var c=a.request("frameCollection"),d=c.getMe().getStringifiedPosition(),b=function(a,b){var c,e,h=b.getStringifiedPosition(),
l=b.inbox;e=!w.embedded;var r=!b.isMe&&!b.srcIsEmbedded;e=e&&b.isMe?"m":e||r?"n":"d";"m"===e?c=h+"*":"d"===e&&(e=d&&h&&l.length&&g(h),b.isValidForMapping()&&e&&(c=f(l,h)));return c},f=function(a,b){var c="";a.length&&(c+=e(a).stringify(function(a,c){var d;d=l.asid===c.srcAsid?b+"*":c.srcAsid&&c.transferDuration?b+"."+c.srcAsid+"."+c.transferDuration:void 0;return d},"|"));return c},g=function(a){return 0===d.indexOf(a)||0===a.indexOf(d)};return{output:function(){var a=e(c.list).stringify(b,"|");return a=
120<a.length?a.substr(0,120)+".of"+a.length:a},isCandidateForMyIdMap:function(a){return a.srcIsEmbedded&&w.embedded&&g(a.getStringifiedPosition())}}},lb=function(a,c){var d=!1,b=function(a){var b=l.asid.split("-")[2];return a.hasOwnProperty("messageContent")&&b===a.iasCommonId},f=function(){var b=a.request("frameCollection").getMe();return a.request("adTalkMessage",{self:b,unifiedId:b.unifiedId})},g=function(a,b){return!e(a).find(function(a,c){return c.srcAsid&&c.srcAsid===b.srcAsid})},m=function(){var b=
h.DT_CODES.ADTALK;a.request("frameCollection").markAllTagsAsReported();d||(d=!0);r.trigger("sendDt",b)},k=function(b,f,l){var k,t,y,v;try{k=a.request("frameCollection");t=f.messageContent;y=t.self;var w=k.getMe();w.unifiedId>y.unifiedId&&(w.unifiedId=y.unifiedId);var x;x=s.now()-f.sentTime;f.transferDuration=x;v=k.getFrame(y.id);e.isUndef(v)||e.isUndef(v.selfDescription)||g(v.inbox,f)?(v=v||k.addFrame(b.source,y.id.split("-"),f),v.addInformationFromSrc(f,y),l()):v.addInformationFromSrc(f,y);var z;
b=v;if(c.on("moreAdTalkCalls")){var A=a.request("idMapModule");z=d&&b.hasUnreportedTag()&&A.isCandidateForMyIdMap(b)}else z=!1;z&&m()}catch(B){r.trigger("error",h.ERROR_CODES.ADTALK_DUBIOUS)}};return{sendAdTalkCall:m,sendToKnownFrames:function(){(new Z).send(f)},startListening:function(){(new gb).listen(b,k,f)},validateMessage:b,processMessage:k,createMessage:f}},pb=function(a){a=a||l;var c;a.reqquery?c=a.reqquery.split(/(?:anId=|anid=|ANID=)([^&]*)/)[1]:(c=a.adsafeSrc.split("/"),c=c[5]+"-"+c[6]);
return{tagId:c,adSafeId:a.asid,isReported:!1}},kb=function(){var a=[];return{createNew:function(c){c=new pb(c);a.push(c);return c},getAll:function(){return a}}},Qa=function(a,c,d){var b=!1,f=function(){c.impressionIsIdentifiable()&&!b&&(b=!0,r.trigger("notify",l._onMeasurable))};return{start:function(){var b=r.request("mobileApp");if(b.isMobileAppEnvironment()?b.isMeasurable():!d.useFlash())f();else r.on("measurable",function(){a.browserIs(h.BROWSERS.WEBKIT)||f()})},isApplicable:function(a){return a.bootstrapOn("useViewabilityNotification")&&
e.isDef(l._onMeasurable)}}},Ma=function(a,c,d,b,f,g,m,k,q,n,p,r,C,y){var v,A,E,z,G=0,H=0,J,N=-1!==l.mode.indexOf("jsvid"),M=g.request("mobileApp"),O=N?200:100;d=l.mobOrTab;var P=!d&&b.on("recordalternate"),T=a.hasFlashEnabled(),I=b.on("forcecocoa")&&T,U=a.getDocumentMode(),U=a.browserIs(h.BROWSERS.GECKO)||a.browserIs(h.BROWSERS.IE)&&(9===U||10===U)&&b.on("rattie"),X=w.friendlyIframe&&I||w.xDomainIframe&&U&&I||w.xDomainIframe&&!U,K=!d&&X&&b.on("cocoapuffs")&&T,Q=!1,R=new ib(10),L=[N&&b.on("videotwoseconds")?
2E3:1E3,5E3,15E3];b.on("everySecond")&&(L=[1E3,2E3,3E3,4E3,5E3,6E3,7E3,8E3,9E3,1E4,11E3,12E3,13E3,14E3,15E3]);var S=e(L).map(function(a,b){return b/1E3}).join("-"),aa=new fa(1E3),W=new ea(n.getPingJobs(L));if(b.on("hundredpct")&&l.use100v)var ba=new fa(1E3),Y=new ea(n.getFullyInViewPingJobs(L));if(b.on("tabHiddenDtCall"))var ca=new fa(1E3),Z=new ea(n.getPosInViewPingJobs([L[0]]));var ga=function(){$();b.on("viewabilityready")&&(c.send(h.DT_CODES.VIEWABILITY_READY),g.trigger("measurable"))};g.on("delayedViewabilityReady",
ga);var $=function(d){try{R.start();var m,n,k,t,w,x;k=r.collect();P&&(k.gState=k.viewState);if(M.isMobileAppEnvironment())k.viewState=M.getViewabilityResult(),k.method=M.getDetectionMethod();else if(K){v=v||new da(V,k.adDimensions,ga,b,p,a)||{};t=v.checkViewable();b.on("hundredpct")&&l.use100v&&(z=z||new bb(ab,k.adDimensions,ga,a,b,f,q,p)||{},w=z.checkViewable(),k.fullPercentInView=w.pct,k.useCocoa=K);if(1!==k.tabHidden||t.str===h.NA)k.viewState=t.str;k.percentInView=t.pct;b.on("unreliabilityDetection")&&
T&&(E=E||new da(V,F({height:0,width:-2E4}),e.noop,b,p,a)||{},x=E.checkViewable(),x.str!==h.OUT_OF_VIEW&&(H+=1),G+=1,q.addItem({output:H+"/"+G},"fu"))}else X&&(k.viewState=h.NA,k.percentInView=-1);P&&(A||d||!T||(A=K?v:new da(V,k.adDimensions,e.noop,b,p,a,f)),k.fState=d||!T?h.NA:A.checkViewable().str);if(N&&(n=y.getViewStateOverride())){if(n===h.OUT_OF_VIEW){var B=k.reason?k.reason.split("."):[];B[B.length]=h.OUT_OF_VIEW_REASONS.VIDEO;k.reason=B.join(".")}k.viewState=n}m=C.registerLocation(k);b.on("hundredpct")&&
l.use100v&&(m.isFullyInView()?(ba.mark(),Y.doEligibleJobs(ba.getTotalTime()),!b.on("zeroPing")||Q||d||(c.send(h.DT_CODES.FULLY_INVIEW,0),Q=!0)):ba.stop());m.isInView()?(aa.mark(),W.doEligibleJobs(aa.getTotalTime())):aa.stop();var I=W.getNextJob();I&&I.time===L[0]&&b.on("tabHiddenDtCall")&&(k.posViewState===h.IN_VIEW||k.posViewState===h.PARTIAL_VIEW_PLUS?(ca.mark(),Z.doEligibleJobs(ca.getTotalTime())):ca.stop());R.stop();var J=s.round(R.getTime()/R.getCount());q.addItem({output:J},"lt",{type:h.DT_CODES.UNLOAD});
return m}catch(O){g.trigger("error",h.ERROR_CODES.CHECK_SCREEN_LOC)}},ha,ia=function(a){var b;J=!0;var d=!1,f=function(){d||(d=!0,c.send(h.DT_CODES.VIDEO_EVENTS))};a=function(){f();if(!ha){var a=[v,z,A,E];b&&clearInterval(b);e(a).each(function(a,b){b&&"function"===typeof b.removePixels&&b.removePixels()});ha=!0}};m.impressionIsIdentifiable()&&($(),b=setInterval($,O),ha=!1,g.on("adStopped",a),g.on("adVideoComplete",a),g.on("skipAd",a),B.addEvent(t,"beforeunload",c.unload,!1),N&&B.addEvent(t,"beforeunload",
f,!1))};return{checkScreenLoc:$,init:function(){"true"===l.allowViewability&&e.isFunction(x.addEventListener)?(J=!1,"complete"==x.readyState||"loaded"==x.readyState||"interactive"==x.readyState?s.execAtEndOfThread(ia):x.addEventListener("DOMContentLoaded",ia,!1)):k.waitForBody(ia)},needsFlash:function(){return X},readyFired:function(){return J},useFlash:function(){return K},stringifyPingTimes:function(){return S}}},la=function(a){var c=new qb,d=new rb,b=new S,e=new sb(b),g=tb(b);try{a.bootstrapOn("mobOrTab")&&
(c.detect(),c.hasDetectedMobileApp()&&(d.detect(),a.on("mraidinjection")&&(d.isSafeToInjectMraid()?e.inject():r.trigger("addOutputItem",{output:"na"},"mi",{type:"impression"}))))}catch(m){r.trigger("error",h.ERROR_CODES.MOBILE_APP)}return{isMobileAppEnvironment:function(){return c.hasDetectedMobileApp()},isMeasurable:function(){return g.isMeasurable()},getViewabilityResult:function(){return g.getViewabilityResult()},getDetectionMethod:function(){return g.getDetectionMethod()}}},ub={url:{STRINGIFIED_METHOD:"u",
detect:function(a){return!!e(a).findFirst(function(a,d){return-1!==s.getWindow().location.href.indexOf(d)})}},userAgent:{STRINGIFIED_METHOD:"a",detect:function(a){return!!e(a).findFirst(function(a,d){var b;b=!1;var f=s.getWindow();e.isDef(f.navigator)&&e.isDef(f.navigator.userAgent)&&(b=(b=f.navigator.userAgent)&&-1!==b.indexOf(d));return b})}},javascript:{STRINGIFIED_METHOD:"j",detect:function(a){return!!e(a).findFirst(function(a,d){return e.isDef(s.getWindow()[d])})}},scriptSrc:{STRINGIFIED_METHOD:"s",
detect:function(a){return!!e(a).findFirst(function(a,d){return A.containsScriptTagWithSrc(function(a){return e.isDef(a)&&-1!==a.indexOf(d)})})}}},ka=function(){var a=function(a,d){var b,e=ub[a];e.detect(d)&&(b=e.STRINGIFIED_METHOD);return b};return{process:function(c){return e(c).map(a).join("")}}},vb={url:["file:","content:","applewebdata:"],userAgent:["QuantcastSDK","afma-sdk"],scriptSrc:["file:"],javascript:["ADMARVEL","mopubFinishLoad","InmobiObj"]},qb=function(){var a,c=function(){return void 0!==
a&&""!==a};return{detect:function(){a=ka().process(vb);c()&&r.trigger("addOutputItem",{output:"1"},"mapp",{type:"impression"})},hasDetectedMobileApp:c}},tb=function(a){var c=new wb(a);return{isMeasurable:function(){return c.isMeasurable()},getViewabilityResult:function(){var a=h.NA;c.isMeasurable()&&(a=c.getViewabilityResult());return a},getDetectionMethod:function(){var a=h.NA;c.isSupported()&&(a=c.getDetectionMethod());return a}}},sb=function(a){var c=function(){a.trigger("injectedMraidJsLoaded")};
return{inject:function(){var a=e.isDef(s.getWindow().mraid),b=A.containsScriptTagWithSrc("mraid.js");(a=!a&&!b)&&r.trigger("exec","mraid.js",c);r.trigger("addOutputItem",{output:e.stringifyTriState(a)},"mi",{type:"impression"})}}},wb=function(a){var c=!1,d=!1,b=!1,f=s.getWindow(),g=function(){var a=f.mraid;return e.isDef(a)&&e.isDef(a.isViewable)},m=function(){var a=f.mraid;g()&&(c=!0,"loading"===a.getState()?a.addEventListener("ready",function(){d=!0;l()}):l())},k=function(){return g()&&b},l=function(){b=
!0;d&&k()&&r.trigger("delayedViewabilityReady")};m();a.on("injectedMraidJsLoaded",function(){c||(d=!0,m())});return{isSupported:g,isMeasurable:k,getViewabilityResult:function(){var a=h.NA;k()&&(a=f.mraid.isViewable()?h.IN_VIEW:h.OUT_OF_VIEW);return a},getDetectionMethod:function(){return h.DETECTION_METHODS.MRAID}}},rb=function(){var a=[],c=[],d=function(b,c){var d,e=ka().process(c.detectionRules);e&&(a.push(c.STRINGIFIED_SDK+"*"+e),d=c);return d};return{detect:function(){c=e(xb).map(d);0<c.length&&
r.trigger("addOutputItem",{output:function(){return a.join(".")}},"sdk",{type:"impression"})},isSafeToInjectMraid:function(){return 1==c.length&&e.isDef(c[0].safeToInjectMraid)&&c[0].safeToInjectMraid}}},xb=[{STRINGIFIED_SDK:"adma",detectionRules:{javascript:["ADMARVEL"],url:["AdMarvel"]}},{STRINGIFIED_SDK:"admb",safeToInjectMraid:!0,detectionRules:{userAgent:["afma-sdk"]}},{STRINGIFIED_SDK:"imbi",safeToInjectMraid:!0,detectionRules:{javascript:["InmobiObj"]}},{STRINGIFIED_SDK:"mmed",detectionRules:{url:["mmsdk"],
scriptSrc:["mmsyscache"]}},{STRINGIFIED_SDK:"mopb",safeToInjectMraid:!0,detectionRules:{javascript:["mopubFinishLoad"]}}],yb=function(a,c){var d=!1,b=!1,f,g=function(){d||(d=!0,f=c.createViewabilityTracker("mpt",function(a){return a.isFullyInView()}))},m=function(a){if(!e.isUndef(a)){var b=-1;e.isDef(a.volume)?b=a.volume:e.isDef(a.adVolume)&&(b=a.adVolume);return b}},k=function(a){a=m(a);d||0!==a?d&&(b||0===a)&&(a={isFullyInView:function(){return!1}},f.addState(a)):b=!0};return{init:function(){a.on({adStarted:g,
adVideoStart:g,volumeChanged:function(a){k(a)},adVideoMidpoint:function(){f&&f.hasAlwaysBeen(!0)&&a.trigger("sendDt",h.DT_CODES.QUARTILE_FULLY_INVIEW)}})}}},zb=function(a,c){var d,b,f=a.eventData;b=function(a){var b=a.charAt(0).toLowerCase()+a.slice(1),c={AdPaused:"pauseAd",AdVolumeChange:"volumeChanged",AdPlaying:"resumeAd"};a in c&&(b=c[a]);return b}(a.messageType);d=e({t:a.time-l.birthdate,tp:b,vid:a.id,sl:c}).mixin(f);return e({indicatesPlaying:function(){return-1!=="showAd|adStarted|adVideoStart|resumeAd".indexOf(b)},
indicatesNotPlaying:function(){return-1!=="adVideoComplete|adStopped|stopAd|pauseAd".indexOf(b)},indicatesFullscreen:function(){var a=s.getWindow();return("resizeAd"===b||"initAd"===b)&&("fullscreen"===f.viewMode||f.width===a.screen.width)},indicatesNormalSize:function(){return"resizeAd"===b&&"normal"===f.viewMode},trigger:function(){r.trigger(b,f)},toString:function(){return"{"+e(d).toParams()+"}"}}).mixin(d)},Ab=function(){var a=[];return{registerEvent:function(c,d){var b=new zb(c,d);a.push(b);
return b},toString:function(){return"{"+e({vEventCount:a.length,vEvents:"["+a.join(",")+"]"}).toParams()+"}"}}},Da=function(a,c,d){var b,f=h.OUT_OF_VIEW,g=s.getWindow(),m=s.getDoc(),k=new Ab;r.provide({videoEventsString:k,videoVersion:function(){var a=n();return a?a.getVersion():-1}});var q=function(b,c){var d=c["IASid"+a],f=e.isFunction(d);f&&(d=d.call(c,a),e.isStr(d)&&r.trigger("addOutputItem",{output:d},"vc",{type:"impression"}));return f},n=function(){b||(e([".integral-vid-"+a,"ias-ad","object",
"embed"]).findFirst(function(a,c){var d=m.querySelectorAll(c);return b=e(e(d).toArray()).findFirst(q)}),b||__IntegralASDiagnosticCall("novidnode",{},l));return b};r.on("videoBlockResult",function(b){var c=n(),d=!1,f="blockAd"+a;"failed"===b.action&&(d=!0);if(c&&e.isDef(c.blockAd))c.blockAd(d);else if(c&&e.isDef(c[f]))c[f](d)});(function(){var b=!1,e=!1;c.on("hundredpct")&&c.bootstrapOn("use100v")&&(new yb(r,d)).init();B.addEvent(g,"message",function(c){var g={};try{g=JSON.parse(unescape(c.data))}catch(l){g=
{}}g.id==a&&(c=k.registerEvent(g,d.getCurrentLoc()),c.indicatesPlaying()?(b=!0,f=e?h.IN_VIEW:!1):c.indicatesNotPlaying()?(b=!1,f=h.OUT_OF_VIEW):c.indicatesFullscreen()?(e=!0,f=b?h.IN_VIEW:h.OUT_OF_VIEW):c.indicatesNormalSize()&&(e=!1,f=b?!1:h.OUT_OF_VIEW),c.trigger())})})();n();return{findAdNode:n,getViewStateOverride:function(){return f}}};try{Xa()}catch(Bb){__IntegralASDiagnosticCall("main",Bb,l)}};
try{(function(){var l=__IntegralASConfig.useFIF?window.parent:window;__IntegralASConfig.initialize(__IntegralASConfig,l,l.document)})()}catch(err$$11){__IntegralASDiagnosticCall("initialize",err$$11,__IntegralASConfig)};
